### ISSUE TITLE
Is this repository ready for production use?

### ISSUE THREAD

**Issue by therealmitchconnors** [oasis-tcs/odata-openapi#1]
If so, could we mark one of the latter commits as a 'release'?

**Comment by ralfhandl** [comment]
Hi Mitch,

The content of this repository is not  "released" for "production use" in any meaning of these words.

You can use the content of this repository for any purpose that is covered by [LICENSE.md](https://github.com/oasis-tcs/odata-openapi/blob/master/LICENSE.md), including purposes that you may call "production use".

Please note that the tools have known gaps, documented in comments within the source code, and that they surely have unknown gaps.

Contributions are welcome, please check [CONTRIBUTING.md](https://github.com/oasis-tcs/odata-openapi/blob/master/CONTRIBUTING.md) on how to do this.

Thanks
Ralf
