### ISSUE TITLE
odata2openapi2 and transform.sh parity

### ISSUE THREAD

**Issue by vminnocci** [oasis-tcs/odata-openapi#10]
The files generated from odata2openapi and transform do not appear to be the same.  Perhaps I'm not using the exec correctly.

If I want to generated a 3.0 spec file from _transform_ I do the following..
transform.txt
_qa-4-metadata.xml http localhost /Core-Informatics/odata/1.0 V4_

What would be the odata2openapi equivalent?

_odata2openapi --basePath /Core-Informatics/odata/1.0 qa-4-metadata.xml_

[qa-4-metadata.zip](https://github.com/oasis-tcs/odata-openapi/files/1981235/qa-4-metadata.zip)

**Comment by ralfhandl** [comment]
The transform script produces both Swagger 2.0 and OpenAPI 3.0.0 output, one suffixed with `.openapi.json`, the other with `.openapi3.json`. It also produces a diagram (`-d`) and a "References" section (`-r`) and runs the resulting JSON files through a pretty-printer (`-p`). So the full equivalent would be

    odata2openapi -drp --scheme http --host localhost --basePath /Core-Informatics/odata/1.0 qa-4-metadata.xml

then rename the OpenAPI 3.0.0 output and run again to produce Swagger 2.0

    odata2openapi -drp -o 2.0 --scheme http --host localhost --basePath /Core-Informatics/odata/1.0 qa-4-metadata.xml

The pretty-printed output may differ due to the different pretty-printers used (`json_reformat` versus `JSON.stringify()`).

**Comment by vminnocci** [comment]
Ralf,
There a number of issues with running odata2openapi.  I removed the -drp options and it managed to create a file, but I think it's malformed because Swagger can't parse it. Again, I tried both commands mentioned above with options is fails and without a malformed file is generated.

**Comment by ralfhandl** [comment]
Please fetch https://github.com/oasis-tcs/odata-openapi/commit/3292a8a3a521da37745e8a446f7a64f10af21414 and omit the -drp options. With that the output runs fine on my local Swagger UI.

Background: `odata2openapi` uses the XSLT processor built into Java, which is somewhat dated and has problems with applying templates to a variable containing a set of nodes. The `transform` script uses the latest Xalan Java XSLT processor that doesn't have that limitation, so I didn't spot the problem. After simplifying `V4-CSDL-to-OpenAPI.xsl` now both XSLT processors produce the same result.

The options -drp aren't useful for your large metadata: you don't have references, the diagram is too large for the diagramming web service, and pretty-printing just adds megabytes of whitespace that will be ignored by Swagger UI anyway.

**Comment by vminnocci** [comment]
Fixed!  Thanks again!
