### ISSUE TITLE
Multi EntityContainer

### ISSUE THREAD

**Issue by iErikSmelt** [oasis-tcs/odata-openapi#103]
Creating an OData $metadata with multiple schemas is not an issue. However, if more than one of these individual schemas contain an EntityContainer, the translation into OpenAPI 3.0.0 JSON fails because of a missing comma (,). Adding the following code block after '<xsl:template match="edm:EntityContainer" mode="paths">' seems to resolve this issue:

    <xsl:if test="position()>1">
      <xsl:text>,</xsl:text>
    </xsl:if>

**Comment by ralfhandl** [comment]
Hi @iErikSmelt, this tool is aimed at OData V4, which does not allow multiple entity containers per schema.

**Comment by iErikSmelt** [comment]
Ralf,

First of, I appreciate the feedback.
I'm not sufficiently aware of the OData standard, but from what I have seen V4 would support multiple schema in a single $metadata? If this is supported, and more than one of these schemas each have a single EntityContainer element, the JSON generation will fail.


Sincerely/Met vriendelijke groet,



Erik Smelt


[Logo]<https://www.itris.nl/>



Itris B.V.

Nevelgaarde 46

3436 ZZ Nieuwegein

t: 088 0902 100

m: 06 22 79 76 95

e: erik.smelt@itris.nl<mailto:niels.koreman@itris.nl>

________________________________

**Comment by ralfhandl** [comment]
Hi @iErikSmelt, rest assured:

> [13 Entity Container](https://docs.oasis-open.org/odata/odata-csdl-xml/v4.01/odata-csdl-xml-v4.01.html#sec_EntityContainer)
> Each metadata document used to describe an OData service MUST define exactly one entity container.

Kind regards

**Comment by iErikSmelt** [comment]
Ralf,

Love the pun.
Thank you for the info.

Sincerely,



Erik Smelt


[Logo]<https://www.itris.nl/>



Itris B.V.

Nevelgaarde 46

3436 ZZ Nieuwegein

t: 088 0902 100

m: 06 22 79 76 95

e: erik.smelt@itris.nl<mailto:niels.koreman@itris.nl>

________________________________

**Comment by guenni68** [comment]
Hi Ralf,

it seems I wasn't the only one getting confused by the issue. However the fact that you explained to me that the EntityContainer describes the API, ie. ResourcePath etc. it of course does make sense that it has to be unique per document.

I've seen some implementations that for this reason seem to use a single edm:Schema only instead of several which in those cases cause painfully constructed entity set name in order to avoid name clashes.

**Comment by ralfhandl** [comment]
Hi Guenther,

In fact the entity container forms its own sub-namespace, and you can use the same name for an entity set and its/an entity type:
~~~xml
<Schema Namespace="theSchema" Alias="this">
  <EntityContainer Name="theContainer">
    <EntitySet Name="Foo" EntityType="this.Foo" />
  </EntityContainer>

  <EntityType Name="Foo">
    ...
</Schema>
~~~

And yes, the specification text could be more intuitive in some places 😄 

Thanks for the feedback!

**Comment by guenni68** [comment]
Hi Ralf,

if one were to use multiple edm:Schema elements in order to reflect the underlying database more closely, could you provide an example for such a scenario?

I've looked for such examples but couldn't find one. I think the scenario where one would want to use multiple edm:Schema is actually not that rare but it does leave some uncertainty on how and where to fit in the essential edm:EntityContainer.

**Comment by ralfhandl** [comment]
Hi Guenther,

What I've seen is:
* one schema that only defines the entity container and does not define any types
* one or more schemas that define the types

I think it is a matter of taste whether to avoid type name clashes by grouping types into different namespaces or whether to use different prefixes for the types in one namespace.

A situation where I would use several schemas:
* reuse types, actions, and functions that I only want to define once are grouped by "topic" into a schema
* that schema can then be hosted separately and reused via `<edmx:Reference ...><edmx:Include .../>...`, or
* the schema can be physically included (copied) into the service's `$metadata` to avoid additional round-trips for clients, or to cater for clients that don't know how to follow an `<edmxReference ...>`.

For example I could have "like" and "dislike" or "follow" and "unfollow" actions that I want to allow everywhere. These are grouped into  a reuse schema, and then referenced or copied as a schema.
