### ISSUE TITLE
Mandatory fields are not set as required in schema

### ISSUE THREAD

**Issue by brunohaller** [oasis-tcs/odata-openapi#104]
Hi,

I have an attribute which is annotated to be mandatory:

```
<Annotations Target="service.ProjectServiceV1.Projects/status">
  <Annotation Term="Common.FieldControl" EnumMember="Common.FieldControlType/Mandatory"/>
</Annotations>
```

and would expect that it results in a requires block on the schema data type like that:

```
"required": [
  "status"
]
```

but it doesn't. 

Best Regards,
Bruno

**Comment by ttrapp** [comment]
I think it is an important use case sind in SAP applications BOPF objects that are exposed via NW GW use those annotations. There was a solution here: [https://github.com/oasis-tcs/odata-openapi/issues/11](https://github.com/oasis-tcs/odata-openapi/issues/11) I tried it again but it doesn't seem to work under CSDLs of BOPF objects in NW 7.53 (Odata V2).

**Comment by brunohaller** [comment]
I saw your issue https://github.com/oasis-tcs/odata-openapi/issues/11 also and tried it, but for some reason it does not work.

Actually I do not come from the BOPF world, but use [CAP](https://cap.cloud.sap/) and CDS modelling.

The cds annotation 

`@mandatory`

is transformed to 

`<Annotation Term="Common.FieldControl" EnumMember="Common.FieldControlType/Mandatory"/>`

by the CDS compiler and than we end up in the same situation :-)

**Comment by ralfhandl** [comment]
Hi @brunohaller, which incarnation of the tool are you using?

The old XSLT-based variant in https://github.com/oasis-tcs/odata-openapi/tree/master/tools should correctly interpret FieldControl/Mandatory.

The new JavaScript-only variant in https://github.com/oasis-tcs/odata-openapi/tree/master/lib intentionally only supports OASIS standard annotations, no SAP annotations, see https://github.com/oasis-tcs/odata-openapi/blob/master/doc/Annotations.md

**Comment by brunohaller** [comment]
HI @ralfhandl ,

I am using https://github.com/oasis-tcs/odata-openapi/blob/master/lib/csdl2openapi.js  so I understand what is the problem.

Should I go back to the old version? Or what would you suggest me to get from a CDS model to required fields in OpenAPI.

Best Regards,
Burno

**Comment by ttrapp** [comment]
@ralfhandl Unfortunately not. The XSLT transformation doesn't interpret

`<Annotation Term="Common.FieldControl" EnumMember="Common.FieldControlType/Mandatory"/>`

correctly.

**Comment by ralfhandl** [comment]
@ttrapp Could you please provide me with a minimalistic example?

**Comment by ralfhandl** [comment]
@ttrapp thanks for the example: found a small bug when bringing it into a test case.

If you annotate a property like this:
https://github.com/oasis-tcs/odata-openapi/blob/2a3315d564ce5894f13adbc1a163294020a0a186/tools/tests/annotations.xml#L305-L308

it becomes `required` in the CREATE structure:
https://github.com/oasis-tcs/odata-openapi/blob/2a3315d564ce5894f13adbc1a163294020a0a186/tools/tests/annotations.openapi3.json#L2926-L2930

Note: it is only required in CREATE requests because in PATCH requests it can be omitted if it is not to be changed, and in GET responses it is omitted if not in `$select`.

**Comment by joergmann** [comment]
Hi @brunohaller

thanks for reporting this. We put this requirement into our backlog.

Best regards
Jörg

**Comment by brunohaller** [comment]
Hi @joergmann , perfect!

In the meantime I created a workaround and manually merge an extension JSON into the generated one, which contains the missing info for the create requests. 

That is good enough for now, and we can close the issue if you like. Can you send me a reference to the backlog item? If it is an internal link, you can also send it to me via company e-mail.

Thank you,
Bruno
