### ISSUE TITLE
Image from yuml.me not shown for big models because yuml.me answers with 414 Request-URI Too Large

### ISSUE THREAD

**Issue by DerGuteWolf** [oasis-tcs/odata-openapi#112]
The transformation generates for the graphical image a yuml.me link. For BIG models yuml.me responds with "414 Request-URI Too Large". yuml.me does this only for direct GET requests. If I copy the yuml.me model string to the yuml.me web page an image is generated.
Unfortunatly our big models are internal so I can't attach or link them as an example here.

**Comment by ralfhandl** [comment]
The generated OpenAPI files are typically used "passively" in Swagger UI or Swagger Editor, and the GET-link works fine in that environment for sufficiently small models. Diagram generation has to be turned on explicitly, so large models can be translated without the diagram.

An alternative for large models would be to use a POST API for yuml.me, fetch the image, place it somewhere, and link to the image in the OpenAPI file.

This however needs lots of assumptions about how the OpenAPI files are used, so I have no plans going into that direction.

How about factoring out the diagram generation into an exported function `csdl2yuml` returning just the diagram notation without the GET wrapper?

Then you can use it in a personal wrapper tool that "knows" about your environment and how to POST to yuml.me.

And of course I would gladly review a pull request that factors out `csdl2yuml` 😄

**Comment by gregorwolf** [comment]
@DerGuteWolf did you try anything of what @ralfhandl suggested?

**Comment by DerGuteWolf** [comment]
@gregorwolf  Well, we use this from https://github.com/geert-janklaps/abap-openapi-ui https://blogs.sap.com/2019/09/03/abap-openapi-ui-v1-released/ https://blogs.sap.com/2022/03/31/abap-openapi-ui-v2-a-long-overdue-update/ ). And so far we did not try to remodel this to use POST. We did manually copy the generated string to the yuml.me web page.
