### ISSUE TITLE
Generation from v2 OData to openAPI - count type definition

### ISSUE THREAD

**Issue by DirtyAssign** [oasis-tcs/odata-openapi#113]
Count type definition is not distinct.
count: {
anyOf: [
{
type: "number"
},
{
type: "string"
}
],
description: "The number of entities in the collection. Available when using the [$count](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptioncount) query option."
},

Problem description: This occurs to a generation problem from openAPI to a java client project from swagger ui 
Generate Client -> Java. 

This can be solved, if count is set to: type: "number" only. 
We have successfully tested. 

-> Solution:
count: 
{
  {
  type: "number"
  }
}

**Comment by ralfhandl** [comment]
Hi  @DirtyAssign,

actually in OData V2 the `__count` is a string;
![image](https://user-images.githubusercontent.com/951576/104306838-c16bdd80-54ce-11eb-8793-1d383cc6dcc8.png)

Can you please check whether your preferred client code generator also can cope with `"type":"string"`?

Thanks in advance
Ralf
