### ISSUE TITLE
Convert ABAP Type dats into string ($date) with pattern YYYY-MM-DD, but OData knows edm.datetime only

### ISSUE THREAD

**Issue by DirtyAssign** [oasis-tcs/odata-openapi#134]
We are using a RDS OData Service , read and write Operation between OData and microservices. 
The CDS-View has got a field dats called "Erstellungsdatum". 
OData generate a edm.dateTime correctly in the $metadata. 
Pattern is: 
datetime'yyyy-mm-ddThh:mm[:ss[.fffffff]]' NOTE: Spaces are not allowed between datetime and quoted portion. datetime is case-insensitive

The openAPI should produce that:
Erstellungsdatum:
  type: string
  nullable: true
  format: date-time
  title: Erstellungsdatum
  example: "2017-04-13T00:00:00Z"

But it produce currently this:
        Erstellungsdatum:
          type: string
          nullable: true
          format: date
          example: '2017-04-13'
          title: Erstellungsdatum

The problem is, in our JAVA project is this attribute 'Erstellungsdatum' send to SAP-Backend, especially OData Entity, which has the Pattern from Edm.DateTime 'yyyy-mm-ddThh:mm[:ss[.fffffff]]'

if the OData Edm.DateTime is set to an attribute, then we need the correct pattern from edm.DateTime (https://www.odata.org/documentation/odata-version-2-0/overview/)

**Comment by ralfhandl** [comment]
Looks like you are still using OData V2.

Please make sure to set the parameter `odata-version` to `2.0` when calling `V4-CSDL-to-OpenAPI.xsl`:

https://github.com/oasis-tcs/odata-openapi/blob/80057f6ef84784b2cfb0bcc71a6b7ff517656a1c/tools/V4-CSDL-to-OpenAPI.xsl#L46

The JavaScript wrapper `transform.js` automatically does this when it detects OData V2 input.

**Comment by DirtyAssign** [comment]
Hi Ralfhandl, 

thank you for your support! I've added odata-version 2.0, when we are using OData V2, 
otherwise for  OData V4 we use odata-version 4.0.

**Comment by ralfhandl** [comment]
Hi @DirtyAssign,

Does it work now as you expect?

If yes, please close this issue.

Thanks!
Ralf

**Comment by DirtyAssign** [comment]
Hi @ralfhandl, 
the data type transformation works fine, now. 
but the mapping is broken.  
setting: 
OData V2 set 2.0 for V4-csdl-to-OpenAPI.xsl 

result (which not work): 
        to_pkfo_massn_120:
          type: object
          properties:
            results:
              type: array
              items:
                $ref: '#/components/schemas/GKV.PA01_P_EHKP_SRV.xGKVxPA01_C_P_KFO_Massn_120Type'


old result date-format does not work, but mapping works fine. (OData V2 with odata-version 4.0 for V4-csdl-to-OpenAPI.xsl)
        to_pkfo_massn_120:
          type: array
          items:
            $ref: '#/components/schemas/GKV.PA01_P_EHKP_SRV.xGKVxPA01_C_P_KFO_Massn_120Type'

In both results  are 
V4-CSDL-to-OpenAPI.xsl and V2-to-V4-CSDL.xsl used.

**Comment by ralfhandl** [comment]
Hi @DirtyAssign, could you please explain in more detail what you mean by "the mapping is broken"?

Can you provide the $metadata file you are converting, or a "minimal" $metadata that shows your problem?

**Comment by DirtyAssign** [comment]
We are converting the openAPI into a java client project
org.openapitools 
openapi-generator-maven-plugin
My JAVA colleague mean the object itself is changed after my changes from version 4.0 to odata-version 2.0, which cause to unresolved mapping problems. 

I need to talk internally, if I can show you the document/metadata.

Changes
from 
```
        to_pkfo_massn_120:
          type: array
          items:
            $ref: '#/components/schemas/GKV.PA01_P_EHKP_SRV.xGKVxPA01_C_P_KFO_Massn_120Type'
```

to: 
```
        to_pkfo_massn_120:
          type: object
          properties:
            results:
              type: array
              items:
                $ref: '#/components/schemas/GKV.PA01_P_EHKP_SRV.xGKVxPA01_C_P_KFO_Massn_120Type'
```

**Comment by ralfhandl** [comment]
This is an expected change. 

OData V4 payload for expanded navigation properties is just the array of expanded entities:
~~~json
"to_pkfo_massn_120":[ <objects for related entities go here> ]
~~~

OData V2 payload has an additional `results` wrapper object:
~~~json
"to_pkfo_massn_120": { "results": [ <objects for related entities go here> ] }
~~~

**Comment by DirtyAssign** [comment]
Hi @ralfhandl. We will check the changes after our releases. Maybe we have to set other configuration in the openapi-genartor-maven-plugin.

Thank you for your support!

Best Regards 

Felix
