### ISSUE TITLE
$batch documentation

### ISSUE THREAD

**Issue by Tiberriver256** [oasis-tcs/odata-openapi#14]
Will this eventually support documentation of the $batch endpoint?

I don't see it in the OData v4 docs but I believe it is still supported.
http://www.odata.org/documentation/odata-version-3-0/batch-processing/

**Comment by ralfhandl** [comment]
[Batch Requests](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part1-protocol/odata-v4.01-cs01-part1-protocol.html#sec_BatchRequests) are very important and have been significantly enhanced with OData V4. 

We even introduced [JSON Batch Format](http://docs.oasis-open.org/odata/odata-json-format/v4.01/cs01/odata-json-format-v4.01-cs01.html#sec_BatchRequestsandResponses) because the multipart format isn't for the faint of heart.

However: Swagger UI has no support for multipart request bodies, so showing the `/$batch` path in Swagger/OpenAPI wouldn't help much for those unfamiliar with OData. And those familiar with OData will know that it is there, and how to use it.

What documentation would you expect on the `/$batch` path in addition to a link to the OData specification?

**Comment by Tiberriver256** [comment]
Maybe just a POST /batch$ endpoint, a short description and a link to the OData specification or OData documentation?

Just so developers are aware.

**Comment by fbunsmann** [comment]
I would agree that a short description and a link to the ODATA Specification would definitely help. Below is just a first idea how it could look like in swagger 2.0. Of course it would be great it if the example for this endpoint would use one or more endpoints which actually exist in the specification.

```yaml
paths:
  /$batch:
    post:
      summary: Using the $batch endpoint, multiple requests can be bundled into a single one.
      description: Group multiple operations into a single HTTP request payload, see [Batch Requests](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part1-protocol/odata-v4.01-cs01-part1-protocol.html#sec_BatchRequests). **Please be aware that the try it out functionality is not supported** for this request.
      parameters:
        - name: Host
          in: header
          type: string
          description: Host URL of the service
        - name: Content-Type
          in: header
          type: string
          required: true
          description: Payload Content-Type, e. g. multipart/mixed;boundary=batch_36522ad7-fc75-4b56-8c71-56071383e77b
        - in: body
          name: payload
          schema:
            type: string
            example: |
             --batch_36522ad7-fc75-4b56-8c71-56071383e77b
              Content-Type: application/http 
              
              GET /service/Customers('ALFKI') 
              Host: host
              
              
              --batch_36522ad7-fc75-4b56-8c71-56071383e77b 
              Content-Type: application/http 
              
              GET /service/Products HTTP/1.1 
              Host: host 
              
              
              --batch_36522ad7-fc75-4b56-8c71-56071383e77b--
      responses:
        202:
          description: Batch request accepted
        default:
          $ref: '#/responses/error'
```

**Comment by ralfhandl** [comment]
@fbunsmann and @Tiberriver256 please have a look at this [example with `/$batch`](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/oasis-tcs/odata-openapi/14/examples/batch.openapi3.json#/Batch%20Requests/post__batch): does that meet your requirements?

**Comment by ralfhandl** [comment]
Opened issue for Swagger UI to find out how to get OpenAPI 3.0 example working: https://github.com/swagger-api/swagger-ui/issues/5090

**Comment by fbunsmann** [comment]
Also think that looks really good. Thanks Ralf!

**Comment by ralfhandl** [comment]
Transformation now produces `/$batch` path items, see e.g. [TripPin example](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/TripPin.openapi3.json#/Batch%20Requests/post__batch)
