### ISSUE TITLE
Function bounded to collection is not handled

### ISSUE THREAD

**Issue by grzonu** [oasis-tcs/odata-openapi#15]
I got schema like that 
`<Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="MyNamespace">
	<Function Name="MyFunction" IsBound="true">
		<Parameter Name="bindingParameter" Type="Collection(MyObject)"/>
		<Parameter Name="from" Type="Edm.DateTimeOffset" Nullable="false"/>
		<Parameter Name="to" Type="Edm.DateTimeOffset" Nullable="false"/>
		<ReturnType Type="Collection(MyObject)"/>
	</Function>
...
</Schema>`

And that function is not show present in openapi json

**Comment by ralfhandl** [comment]
Hi @grzonu, 

Yes, this case is not yet supported because I hadn't any use case for it.

Could you please provide an example $metadata?

Thanks in advance
Ralf

**Comment by grzonu** [comment]
Sure,

`<?xml version="1.0" encoding="UTF-8"?>
<edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
   <edmx:DataServices>
      <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Example.Model">
         <EntityType Name="ExampleModel">
            <Key>
               <PropertyRef Name="Id" />
            </Key>
            <Property Name="Id" Type="Edm.Decimal" Nullable="false" />
            <Property Name="Field1" Type="Edm.String" Nullable="false" />
            <Property Name="Field2" Type="Edm.String" Nullable="false" />
            <Property Name="Field3" Type="Edm.Decimal" Nullable="false" />
            <Property Name="Field4" Type="Edm.DateTimeOffset" />
         </EntityType>
      </Schema>
      <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="ExampleService">
         <Function Name="ExampleFunction" IsBound="true">
            <Parameter Name="bindingParameter" Type="Collection(Example.Model.ExampleModel)" />
            <Parameter Name="Parameter1" Type="Edm.DateTimeOffset" Nullable="false" />
            <Parameter Name="Parameter2" Type="Edm.DateTimeOffset" Nullable="false" />
            <ReturnType Type="Collection(Example.Model.ExampleModel)" />
         </Function>
         <EntityContainer Name="Container">
            <EntitySet Name="ExampleModel" EntityType="Example.Model.ExampleModel" />            
         </EntityContainer>
      </Schema>
   </edmx:DataServices>
</edmx:Edmx>`

**Comment by ralfhandl** [comment]
Hi @grzonu,

I finally got around to adding actions and functions bound to a collection. 
Example: http://petstore.swagger.io/?url=https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/miscellaneous.openapi3.json#/Products

Please close the issue if it works for you.

Thanks in advance
Ralf
