### ISSUE TITLE
Error : $ref must reference a valid location in the document

### ISSUE THREAD

**Issue by MIB-Marketing** [oasis-tcs/odata-openapi#156]
Hi, we are performing swagger file generation with your odata open api3 library on CRM Dynamics.
However since a few days we get this type of error : 

Errors

 
Resolver error at components.schemas.Microsoft.Dynamics.CRM.account-create.properties.ownerid.$ref
Could not resolve reference: #/components/schemas/Microsoft.Dynamics.CRM.principal
Jump to line 195
Resolver error at components.schemas.Microsoft.Dynamics.CRM.account.properties.ownerid.$ref
Could not resolve reference: #/components/schemas/Microsoft.Dynamics.CRM.principal
Jump to line 450
Semantic error at components.schemas.Microsoft.Dynamics.CRM.account.properties.ownerid.$ref
$refs must reference a valid location in the document
Jump to line 450
Resolver error at components.schemas.Microsoft.Dynamics.CRM.account.properties.createdby.properties.lk_metric_createdby.items.$ref
Could not resolve reference: #/components/schemas/Microsoft.Dynamics.CRM.metric
Jump to line 451
Resolver error at components.schemas.Microsoft.Dynamics.CRM.account.properties.createdby.properties.lk_metric_modifiedby.items.$ref
Could not resolve reference: #/components/schemas/Microsoft.Dynamics.CRM.metric
Jump to line 451
Resolver error at components.schemas.Microsoft.Dynamics.CRM.account.properties.createdby.properties.lk_goalrollupquery_createdby.items.$ref
Could not resolve reference: #/components/schemas/Microsoft.Dynamics.CRM.goalrollupquery
Jump to line 451
Resolver error at components.schemas.Microsoft.Dynamics.CRM.account.properties.createdby.properties.lk_goalrollupquery_modifiedby.items.$ref
Could not resolve reference: #/components/schemas/Microsoft.Dynamics.CRM.goalrollupquery
Jump to line 451
Resolver error at components.schemas.Microsoft.Dynamics.CRM.account.properties.createdby.properties.lk_position_createdby.items.$ref
Could not resolve reference: #/components/schemas/Microsoft.Dynamics.CRM.position
Jump to line 451
Resolver error at components.schemas.Microsoft.Dynamics.CRM.account.properties.createdby.properties.lk_position_modifiedby.items.$ref
Could not resolve reference: #/components/schemas/Microsoft.Dynamics.CRM.position

CRM Data file version 9.2 

Have you ever faced this kind of issue ? 
We are ready to investigate on this issue.

**Comment by ralfhandl** [comment]
Hi @MIB-Marketing,

Can you please check if the `$ref` points to an existing schema?

Which tool is reporting these errors?

Thanks in advance
