### ISSUE TITLE
odata v2 Annotations with Target won't show up 

### ISSUE THREAD

**Issue by AngeloDellaMorte** [oasis-tcs/odata-openapi#159]
Hello,
I'm trying to add ReadRestrictions via Annotations with Target, but they won't show up.
I tried every possible combination of target names, but nothing works.

It works only if i manually convert my V2 metadata to V4 then copy the annotations directly unter the corresponding EntitySet and then generate swagger json.

Am I doing something wrong?
V2 metadata
![image](https://user-images.githubusercontent.com/24492422/134561900-bc18a5f4-b279-4763-baf5-b68dd2ad382e.png)

V4 metadata
![image](https://user-images.githubusercontent.com/24492422/134561728-53fddc8a-54db-4e17-934b-e0eba76649a1.png)

**Comment by ralfhandl** [comment]
@AngeloDellaMorte Hi Angelo,

I've added a test case for ReadRestrictions and tried to come as closely to your example as possible:

https://github.com/oasis-tcs/odata-openapi/blob/3f1b68959faf2a6975c18e57d9bb7079b7035020/tools/tests/annotations-v2.xml#L43-L54

This works as expected, see

https://github.com/oasis-tcs/odata-openapi/blob/3f1b68959faf2a6975c18e57d9bb7079b7035020/tools/tests/annotations-v2.openapi3.json#L19-L23

https://github.com/oasis-tcs/odata-openapi/blob/3f1b68959faf2a6975c18e57d9bb7079b7035020/tools/tests/annotations-v2.openapi3.json#L178-L180

I cannot spot any difference to your test case: could you please re-check with the latest version of the two XSL transformations?

Thanks in advance!
