### ISSUE TITLE
OData v4 TripPin conversion semantic error

### ISSUE THREAD

**Issue by MartinPankraz** [oasis-tcs/odata-openapi#184]
The v4 example cannot be converted to a proper swagger definition using the [Oasis converter](https://github.com/oasis-tcs/odata-openapi/tree/main/lib).

Find the service metadata here: [https://services.odata.org/V4/TripPinServiceRW/$metadata](https://services.odata.org/V4/TripPinServiceRW/$metadata)

It fails validation on [editor.swagger.io](https://editor.swagger.io/) with

```
Semantic error at paths./People('{UserName}')/Microsoft.OData.SampleService.Models.TripPin.GetFriendsTrips(userName='{userName}')
Parameter names are case-sensitive. The parameter named "userName" does not match the case used in the path "/People('{UserName}')/Microsoft.OData.SampleService.Models.TripPin.GetFriendsTrips(userName='{userName}')".
[Jump to line 402]()
```

Would be great to get perspective where this needs to be addressed.

**Comment by ralfhandl** [comment]
Seems to be a bug in the semantic check in Swagger Editor. The path has two parameters `UserName` and `userName` that differ in case only, but as the check says parameter names are case-sensitive, so this is allowed.

Both parameters in the path have matching definitions in the `parameters` array: 
https://github.com/oasis-tcs/odata-openapi/blob/bbcfab2285ed2b925280b0ef65c54bf4b2f8b174/examples/TripPin.openapi3.json#L617-L641

So all is fine, and the validation in [Swagger UI](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/TripPin.openapi3.json) says
![image](https://user-images.githubusercontent.com/951576/152370203-69d2f391-4cd3-4114-bb98-562ee043614e.png)

**Comment by MartinPankraz** [comment]
Agreed, but there are API Management solutions failing due to this case sensitivity too. Likely executing the same validation. Once I changed the name it become importable again.

**Comment by ralfhandl** [comment]
Well, it would be nice if Swagger Editor could fix this check and accept valid OpenAPI documents.

**Comment by MartinPankraz** [comment]
I have reached out to the support of swagger editor shring our conversation here. Let's see

**Comment by ralfhandl** [comment]
Thanks! If you opened an issue for Swagger Editor, please add a link to it here.
