### ISSUE TITLE
encounter missing symbol called error !!!

### ISSUE THREAD

**Issue by willpowerforever** [oasis-tcs/odata-openapi#188]
I followed instructions in page: https://oasis-tcs.github.io/odata-openapi/tools/ to install.
Then run following command:
`odata-openapi -dp odata_v2_api_metadata.xml`

Receive error:
```
dyld[68636]: missing symbol called
zsh: abort      odata-openapi -dp odata_v2_api_metadata.xml
```

Environment:
OS:	macOS 12.2.1
BuildVersion:	21D62

JDK: SAPJVM8

**Comment by ralfhandl** [comment]
Hi William,

Unfortunately I don't have access to a Mac and cannot troubleshoot installation issues on MacOS.

Why are you trying to use the old XSLT-based tool instead of the new pure JavaScript implementation https://oasis-tcs.github.io/odata-openapi/lib/?

Thanks in advance
Ralf

**Comment by willpowerforever** [comment]
Hi Ralf,

I need to convert an Odata V2 API metadata into OpenAPI. Per the information from the link you provided, it doesn't support Odata v2.

Thanks!
William

**Comment by ralfhandl** [comment]
Hi William,

Which kind of Mac do you have: one of the fancy brand-new M1's? For this architecture Google found this:
* https://gist.github.com/adrienjoly/e29a6e73fb7e701eefd80ff9bde9abeb

Thanks
Ralf

**Comment by ralfhandl** [comment]
The dependency on node-gyp has been removed, installation should now run smoothly.
