### ISSUE TITLE
Publish OData to openAPI as npn package

### ISSUE THREAD

**Issue by fisehara** [oasis-tcs/odata-openapi#192]
Hello,

I'd like to know if there is a plan / roadmap to publish this very handy tool as npm package, so that the dependency management in a project using this translator becomes 

### Our current approach / workaround
Currently we are starting to use this project as a git package dependency in our package.json as:
``` json
"odata-openapi": "git+https://github.com/oasis-tcs/odata-openapi#main"
```

In our module we use this import:
``` javacsript
import * as odataMetadata from 'odata-openapi';
```

As we are using the odata-openapi in a typescript environment we have just added a thin / naive types description file:
``` javascript
declare module 'odata-openapi' {
	export const csdl2openapi: (
		csdl,
		{ scheme, host, basePath, diagram, maxLevels } = {},
	) => object;
}
```

 I'm happy to help to package this repository.
 
#### Alternative workaround
If there is no plan to publish a npm package, I'd like to request that repo releases / tags are created so that the dependency in package.json can be pinned to specific releases version of the repo. Right now it's somehow dangerous / unpredictable to depend on the main branch of the repo.
The underlying npm documentation is here: [git-urls-as-dependencies](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#git-urls-as-dependencies) and specifies to have a version tag or version branch as an identifier in the dependency url.

 Best Regards
 Harald

**Comment by ralfhandl** [comment]
Hi Harald,

the pure JavaScript tool in `lib` is already published as an npm package: https://www.npmjs.com/package/odata-openapi.

I've updated the README to reflect this, and published the latest version.

Thanks for reminding me of it!
Ralf

**Comment by fisehara** [comment]
Hi Ralf,

great news and sorry for bothering you as I just didn't search npm package registry first 😞 

Closing issue.
Best Regards
Harald
