### ISSUE TITLE
OpenAPI does not support multiple input types

### ISSUE THREAD

**Issue by Tiberriver256** [oasis-tcs/odata-openapi#2]
Hi great project!

I used transformed the following metadata url:
http://services.odata.org/V3/OData/OData.svc/$metadata

Received a response that rendered using the Swagger editor:
http://editor.swagger.io/#/

It did generate some response objects as having two possible types like this
```json    
"definitions": {
        "ODataDemo.Product": {
            "type": "object",
            "properties": {
                "ID": {
                    "type": "integer",
                    "format": "int32"
                },
                "Name": {
                    "type": ["string", "null"]
                },
                "Description": {
                    "type": ["string", "null"]
                },
```

Which does not conform to the current OpenAPI spec. It does not look like there is a good way to do it in v2 but if you wanted to conform with the v3 spec null should be as:

```json
"Name": {
                    "type": "string",
                    "nullable": true
                }
```

Multiple types of responses should be something like:

```json
"Name": {
    "oneOf": [
        {"type": "string"},
        {"type": "integer"}
    ]
}
```

v3 spec: https://swagger.io/docs/specification/data-models/data-types/
v2 spec:  https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#header-object

Thanks for working on this!

**Comment by ralfhandl** [comment]
Hi Micah,

Thanks for the feedback, answers see below.

May I ask in which context you are using this tool?

Thanks in advance
Ralf


# Swagger/OpenAPI 2.0

The Swagger/OpenAPI 2.0 specification allows arrays of string values for `type` in the [Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject); the cited restriction to a single string value is only for headers and URL parameters.

The metadata url you mention is the origin of example [odata-rw-v3.xml](https://github.com/oasis-tcs/odata-openapi/blob/master/examples/odata-rw-v3.xml). Its OpenAPI 2.0 transformation output [odata-rw-v3.openapi.json](https://github.com/oasis-tcs/odata-openapi/blob/master/examples/odata-rw-v3.openapi.json) works fine in Swagger UI 2.x and Swagger Editor 2.10.5. 

The online instance of Swagger Editor at http://editor.swagger.io is based on the brand new version 3.x of the combined Swagger UI/Editor, which does not yet cover all features of Swagger 2.0.

The online instance of Swagger UI (also based on the brand new version 3.x) is a little further ahead and works fine with the example, showing a green validator badge: http://petstore.swagger.io/?url=https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/odata-rw-v3.openapi.json

# OpenAPI 3.0.0

The XSL transformation produces OpenAPI 3.0.0 output when setting the script parameter `openapi-version` to `3.0.0`, e.g. [odata-rw-v3.openapi3.json](https://github.com/oasis-tcs/odata-openapi/blob/master/examples/odata-rw-v3.openapi3.json). It produces the new `nullable` keyword for nullable properties. 

This works fine with the online instance of Swagger UI; http://petstore.swagger.io/?url=https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/odata-rw-v3.openapi3.json

It works less well with the online instance of Swagger Editor, which has some problems resolving external references during validation: http://editor.swagger.io/?url=https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/odata-rw-v3.openapi3.json

**Comment by Tiberriver256** [comment]
Hi Ralfhandl,

Thank you for the response and explanation. I am looking for something to use in a Node.js API gateway project that would dynamically display a Swagger UI for Odata endpoints. We are currently using this project https://github.com/akorchev/odata2openapi but it has fallen behind a bit and definitely not as crisp as the json generated from this project.

**Comment by ralfhandl** [comment]
Hi Micah,

Cool! Which XSLT processor are you planning to use?

Thanks in advance
Ralf

**Comment by Tiberriver256** [comment]
I haven't found a great one for Node.js yet. Most have a node-gyp
dependency which is quite painful to set up in a Windows hosted environment.
