### ISSUE TITLE
how to use this repo to convert SAP OData service into Swagger 2.0

### ISSUE THREAD

**Issue by NareshSAP** [oasis-tcs/odata-openapi#20]

**Comment by NareshSAP** [comment]
It is not to report an issue with the repo but to know how this can be used in SAP world to generate Swagger 2.0 spec for SAP based OData service developed using transaction code SEGW.

**Comment by ralfhandl** [comment]
@NareshSAP currently you can only download the $metadata file after activating the service in SEGW and then use these tools on your local machine.

There are plans to embed this into ABAP tools for developing OData services, but I cannot give you a timeline here.

**Comment by Gekke-Jakke** [comment]
@NareshSAP, @ralfhandl,
I created an open source ABAP Project to incorporate these XSLT transformations in the SAP backend.
More details can be found here: 
https://blogs.sap.com/2019/09/03/abap-openapi-ui-v1-released/

**Comment by ralfhandl** [comment]
Cool!

**Comment by NareshSAP** [comment]
Great work!
