### ISSUE TITLE
Odata v2 to v4 to OpenAPI conversion - too many endpoints created

### ISSUE THREAD

**Issue by Mile76** [oasis-tcs/odata-openapi#206]
Hi

I've tested the conversion via an Odata v2 metadata definition and came up with more endpoints in the OpenAPI definition than expected.

I've created two entities and a navigation/relation between them. Expectation were to get 4 endpoints but the navigation was also created as it's own endpoint (see screenshot), I assume that come from the internal conversion to odata v4(?).

![image](https://user-images.githubusercontent.com/35592299/160635319-0a7830b4-e739-4904-8b28-3cde99e80326.png)

Let me know if you need more information and thank you for your work, have a nice day.

Br Michael

**Comment by ralfhandl** [comment]
Hi Michael,

This is the navigation/relation: it can be queried to get just the subset of related "target" entities for a given "source" entity.

The request is possible with both OData V2 and V4, so works as expected.

Thanks for trying out this tool
Ralf
