### ISSUE TITLE
npm install fails on windows 10

### ISSUE THREAD

**Issue by michalhainc** [oasis-tcs/odata-openapi#21]
PS D:\git\github\odata-openapi\tools> npm install
> java@0.11.0 install D:\git\github\odata-openapi\tools\node_modules\java
> node-gyp rebuild
D:\git\github\odata-openapi\tools\node_modules\java>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
D:\git\github\odata-openapi\tools\node_modules\java\build\nodejavabridge_bindings.vcxproj(20,3): error MSB4019: The imp
orted project "D:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is corr
ect, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: ``C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\git\github\odata-openapi\tools\node_modules\java
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN odata-openapi@0.0.0 license should be a valid SPDX license expression
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! java@0.11.0 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.11.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mhainc\AppData\Roaming\npm-cache\_logs\2019-02-22T08_18_19_767Z-debug.log
PS D:\git\github\odata-openapi\tools>`

**Comment by ralfhandl** [comment]
Did you first install `node-gyp` globally, following the [platform-specific installation instructions for `node-gyp`](https://github.com/nodejs/node-gyp/blob/master/README.md#installation)?

If yes, did `node-gyp` install without problems?

**Comment by michalhainc** [comment]
Yes I've done this before you adviced, otherwise I wound't post here ;) , I installed the windows-build-tools as well, but I ended up in a dead end situation described above..
node-gyp installation itself doesnt seem to complain about anything
`PS C:\WINDOWS\system32> npm install node-gyp -g
C:\Users\mhainc\AppData\Roaming\npm\node-gyp -> C:\Users\mhainc\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js
\+ node-gyp@3.8.0
updated 2 packages in 2.847s
`

**Comment by michalhainc** [comment]
Aha, found it... the culprit was to use node-gyp windows specific installation "Option 2" ... for me the 
`npm config set msvs_version 2017` 
resolved my situation

**Comment by ralfhandl** [comment]
Glad to hear that you could solve your problem, never tried node-gyp option 2 myself.
