### ISSUE TITLE
Specific OData XML file cannot be converted, only .tmp file is created

### ISSUE THREAD

**Issue by unhenri** [oasis-tcs/odata-openapi#210]
Hi guys,

first of all a huge thank you for this great tool! It really does help us a lot.

When trying to transform a specific OData XML file my terminal output is:
```
file:///Users/henri/.../odata-openapi/tools/V2-to-V4-CSDL.xsl; line 1176; column 18; EntityType/sap:semantics="subscriptions"
file:///Users/henri/.../odata-openapi/tools/V2-to-V4-CSDL.xsl; line 1176; column 18; EntityType/sap:semantics="notifications"
```
But no further errors. It just creates a .tmp file of the XML and no converted .json file. Other xml files can be converted just fine. 
What could be the issue?

I am using macOs Monterrey.

Thank you and best regards

Henri

**Comment by ralfhandl** [comment]
Hi Henri,

Please try out the latest version of `tools/translate.js`, it should no longer stumble over the warning messages.

Thanks in advance
Ralf

**Comment by unhenri** [comment]
Hi Ralf,
works perfectly now. Danke dir and keep up the great work!
Regards
Henri
