### ISSUE TITLE
Error: spawnSync java ENOENT

### ISSUE THREAD

**Issue by GregoryPauwelsG** [oasis-tcs/odata-openapi#211]
I use this solution in a SAP CAP application. It works fine when tested locally, but after deploying my app, I always get the following:
![image](https://user-images.githubusercontent.com/97838451/169260702-d8533195-5fab-4ad9-ba3f-c19fac666822.png)

Does it have something to do with do with the right permissions to read and write a file in SAP CF (the place where the app is deployed)?

**Comment by ralfhandl** [comment]
Hi @GregoryPauwelsG, I only run this script locally, on Win10 or on WSL with Ubuntu 20.04.3 LTS. Never have seen this error.

**Comment by ralfhandl** [comment]
If you are using OData V4, I recommend switching to the pure JavaScript version of this tool from https://www.npmjs.com/package/odata-openapi, or use the [OpenAPI generator built into CAP](https://cap.cloud.sap/docs/advanced/openapi).

If you are still using OData V2, I strongly recommend switching to OData V4 😉

**Comment by GregoryPauwelsG** [comment]
I think I found what caused this error. Other commands (for example: node --version) do work when the app is deployed so I think that the deployed app has no access to Java in SAP CF.
