### ISSUE TITLE
Edm.Int64 PrimitiveType translated to anyOf["string", "integer"] 

### ISSUE THREAD

**Issue by fisehara** [oasis-tcs/odata-openapi#221]
The current implementation translated a Edm.int64 into a openapi spec type of integer or string. 
The example value is defined as "42" string const. 
Any consumer of the generated openapi spec is failing to identify the data type correctly. 

https://github.com/oasis-tcs/odata-openapi/blob/639dfcca7baba64ce32481352d10d503d7dddffb/lib/csdl2openapi.js#L2796-L2803

As there is a switch mentioned for open api spec 3.1 and the spec: https://spec.openapis.org/oas/v3.1.0#data-types defines int64 as integer, I expect the resulting type to be integer.

**Comment by ralfhandl** [comment]
@fisehara Hi Harald,

Background of this feature is OData's possibility for clients to [control the representation of Decimal and Int64 numbers](https://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#sec_ControllingtheRepresentationofNumber).

Reason is that JavaScript's `JSON.parse` will parse JSON numbers into a [double precision binary floating point value](https://en.wikipedia.org/wiki/Double-precision_floating-point_format), which means there will be loss of precision if a JSON number value has more than 53 binary digits, see [Number.MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER).

A JSON response from a compliant OData service will encode Int64 values as JSON numbers by default, and as JSON strings on client request.

Given that, the correct OpenAPI type is "either number or string", expressed depending on the OpenAPI version used.

Does that answer your question?

Thanks in advance

**Comment by fisehara** [comment]
@ralfhandl Hi Ralf,

thanks a lot for the explanation. Yes this totally answers my question and we are now conceptualising how to consume the resulting openapi spec for the int64 case.

Thanks for the details and the fast reply :)

Harald
