### ISSUE TITLE
Property sap:label is not handled

### ISSUE THREAD

**Issue by IharHal** [oasis-tcs/odata-openapi#246]
Hello there, 
the new version of the odata-openapi [0.23.0] does not support the Property sap:label. Please find an example below:

XML row:
![image](https://user-images.githubusercontent.com/130773044/232083596-9ec0ab80-e220-4be8-8c54-df963425c0d4.png)

conversion with [0.23.0] odata-openapi version:
![image](https://user-images.githubusercontent.com/130773044/232080999-50a4746b-4587-4202-a009-c417e10a250f.png)

conversion with [0.18.3] odata-openapi version:
![image](https://user-images.githubusercontent.com/130773044/232082323-a1547258-b171-4122-8785-117d44021989.png)

could you please take a look?

Thanks in advance,
Ihar

**Comment by ralfhandl** [comment]
Hi @IharHal,

Thanks for the detailed problem description.

This repository contains two implementations with slightly different behavior:
1. An older [XSLT-based implementation](https://github.com/oasis-tcs/odata-openapi/tree/main/tools) that supports OData V2-V4 as input and can produce OpenAPI 2.0-3.0
2. A newer [JavaScript-based implementation](https://github.com/oasis-tcs/odata-openapi/tree/main/lib) that up to and including version 0.18.3 only supported OData V4 as input and can produce OpenAPI 3.0-3.1, and [added OData V2-V3 input with version 0.19.0](https://github.com/oasis-tcs/odata-openapi/blob/main/CHANGELOG.md#0190---2022-10-08)

This means your example for 0.18.3 was produced with the older XSLT-based implementation, which is still available with 0.23.0, and should produce the same output.

Note: the [NPM package](https://www.npmjs.com/package/odata-openapi) only contains the newer JavaScript-based implementation, the older XSLT-based implementation needs to be installed directly from GitHub.

Note: when installed globally, the newer implementation uses the command `odata-openapi3` (with a trailing `3`), and the older implementation uses the command `odata-openapi`.

**Comment by IharHal** [comment]
Hi Ralf,
Thank you for the clarification!

Best regards,
Ihar
