### ISSUE TITLE
<Key> in Schema creates errors

### ISSUE THREAD

**Issue by matbee-eth** [oasis-tcs/odata-openapi#247]
Having a `<Key>` in an `<EntityType>` creates an error-filled "get by key" function.

**Comment by ralfhandl** [comment]
Hi @matbee-eth,

Could you please provide sample input XML that produces this error?

Given the number of working examples with `<Key>` elements I'm curious what makes the difference in your case.

This one works fine, same as the others in the [examples](../tree/main/examples) folder:

https://github.com/oasis-tcs/odata-openapi/blob/f6de9fa5de13929de5ba75bcea541c97b2932d53/examples/ExampleService.xml#L66-L69

Thanks in advance
