### ISSUE TITLE
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by louagej** [oasis-tcs/odata-openapi#252]
Hi,

I have a schema downloaded from a default Business Central API V2
When trying to generate a Odata.openapi3.json, I get this error message:
```
<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF71DAE2BCF node_api_throw_syntax_error+175519
 2: 00007FF71DA683A6 SSL_get_quiet_shutdown+64006
 3: 00007FF71DA69762 SSL_get_quiet_shutdown+69058
 4: 00007FF71E50FDD4 v8::Isolate::ReportExternalAllocationLimitReached+116
 5: 00007FF71E4FB132 v8::Isolate::Exit+674
 6: 00007FF71E37CF8C v8::internal::EmbedderStackStateScope::ExplicitScopeForTesting+124
 7: 00007FF71E37A1AB v8::internal::Heap::CollectGarbage+3963
 8: 00007FF71E3903E3 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath+2099
 9: 00007FF71E390C8D v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath+93
10: 00007FF71E3A04C3 v8::internal::Factory::NewFillerObject+851
11: 00007FF71E0916B5 v8::internal::DateCache::Weekday+1349
12: 00007FF71E5AD371 v8::internal::SetupIsolateDelegate::SetupHeap+558193
13: 00007FF69E82D06F
```

I already increased my assigned memory to 4Gb

![image](https://github.com/oasis-tcs/odata-openapi/assets/7229592/7fcbcf4a-3add-439e-9463-977c6cfa7618)

**Comment by louagej** [comment]
sure,

here it is

[BC_API_V2_edmx.zip](https://github.com/oasis-tcs/odata-openapi/files/11916749/BC_API_V2_edmx.zip)

**Comment by ralfhandl** [comment]
Fixed with odata-openapi@0.23.3

**Comment by ralfhandl** [comment]
Hi @louagej,

The EDMX file makes _heavy_ use of deeply nested composition / containment, which just blows up the resulting OpenAPI file.

I've reduced the default recursion level to 4 (from 5) which allows processing your example, and I've added a new command-line option `--levels` to set the recursion level in case your next example is even heavier on containment 😄.

**Comment by louagej** [comment]
@ralfhandl ,

Thank you. It runs like a charm now!
