### ISSUE TITLE
documentation item

### ISSUE THREAD

**Issue by DennyFiguerres** [oasis-tcs/odata-openapi#260]
for folks who are not familiar with npm
please explain in the doc page what this means:
Switch into the checkout project directory

while i have used npm a bit i am not sure what that means, is this the npm install folder ? is this a folder in the odata-openapi3 install ?
please clarify this....

i think it is the npm\node_modules\odata-openapi folder - is that right ?

when i enter:  npm run build i get this error message:

> odata-openapi@0.23.4 build
> node lib/transform.js

node:internal/fs/utils:350
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir './examples/'
    at Object.readdirSync (node:fs:1527:3)
    at Object.<anonymous> (C:\Users\XXXXXXXXXXX\AppData\Roaming\npm\node_modules\odata-openapi\lib\transform.js:26:4)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
    path: './examples/'
}

Node.js v18.18.2
i guess it is looking for a folder that is not part of the package for some example files ???

or was any of that needed ?  i also see a cmd file and ps file .... i think i can run the command but this is all confusing....

**Comment by ralfhandl** [comment]
If you just want to run the script in a shell, the only step you need is
~~~sh
npm install -g odata-openapi
~~~

Then you can directly use the `odata-openapi3` command on your XML metadata file, no need to "build" anything.

The `npm run build` script only refreshes the OpenAPI files in the `examples` folder.

**Comment by ralfhandl** [comment]
Reduced the documentation to the minimum steps for global installation and command-line use of the `odata-openapi3` script.
