### ISSUE TITLE
gyp error in npm install

### ISSUE THREAD

**Issue by hitesharora2** [oasis-tcs/odata-openapi#29]
I am trying to install node modules in tools 

'" KeyError: '2019'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\hitesh.arora\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hitesh.arora\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\odata-openapi\tools\node_modules\java
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN odata-openapi@0.0.0 license should be a valid SPDX license expression

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! java@0.11.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.11.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hitesh.arora\AppData\Roaming\npm-cache\_logs\2019-05-29T09_51_35_705Z-debug.log""

**Comment by hitesharora2** [comment]
I have multiple python version installed but I have configured the python path to be python 27.

**Comment by ralfhandl** [comment]
Sorry, have only python 2.7 installed, and only for node-gyp. Please refer to the https://github.com/nodejs/node-gyp documentation.

**Comment by hitesharora2** [comment]
I resolved the error by setting Python to 2.7 while installing the modules.It works now
