### ISSUE TITLE
Covert XMl to open api failes

### ISSUE THREAD

**Issue by menaheme** [oasis-tcs/odata-openapi#299]
Hello im trying to convert an OData CSDL file from the ISV "Proirity" (available at https://www.eshbelsaas.com/ui/odata/Priority/tabmob.ini/usdemo/$metadata 
using basic auth (username: apidemo  , password: 123))

attaching the csdl file to the issue.
[priority_odata_service_csdl_metadata.zip](https://github.com/oasis-tcs/odata-openapi/files/15233050/priority_odata_service_csdl_metadata.zip)

i installed the npm and ran the converter as per instructed at :https://oasis-tcs.github.io/odata-openapi/lib/
but the converter fails with the cryptic message: **util.parseArgs is not a function**

**Comment by ralfhandl** [comment]
@menaheme Converting the attached CSDL file works fine for me and produces ~41 MB of OpenAPI.

Which version of Node.js are you using? Please make sure to use at least version 18.

**Comment by menaheme** [comment]
Using node 16, thanks
41mb? Thats probably not going to do

**Comment by ralfhandl** [comment]
You can restrict the generated OpenAPI file to certain root resources by using the option `-k`, for example
~~~sh
odata-openapi3 -k ORDERS response.xml
~~~
That only shows the `ORDERS` entity set and anything directly related to it.

**Comment by menaheme** [comment]
updated node to 20.9 and reduced the schema as suggested resulting in 980Kb (will continu to explore) 
thank you for your prompt and educational responses !
