### ISSUE TITLE
on MacOS...Error processing OData v3.0 $metadata XML file...

### ISSUE THREAD

**Issue by HestonHoltmann** [oasis-tcs/odata-openapi#3]
my odata3-metadata.xml file is from a clients Private (non-public) OData v3.0 web service.

The head of my input file from $metadata file is shown below

hholtmann on hhMacBookPro2014 in ~/proj/iw/openAPI/client
➜  head odata3-metadata.xml 
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="1.0" xmlns:edmx="http://schemas.microsoft.com/ado/2007/06/edmx">
    <edmx:DataServices m:DataServiceVersion="3.0" m:MaxDataServiceVersion="3.0" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
        <Schema Namespace="CMMSdg.Plant.MappingObjects.PublicDTO" xmlns="http://schemas.microsoft.com/ado/2009/11/edm">
            <EntityType Name="POReceiptDTO">
                <Key>
                    <PropertyRef Name="POID" />
                </Key>
                <Property Name="POID" Type="Edm.String" Nullable="false" />
                <Property Name="LineNo" Type="Edm.Int32" Nullable="false" />
hholtmann on hhMacBookPro2014 in ~/proj/iw/openAPI/cmms 

No problems installing Node.js and other packages required for macOS

But i get errors when i try to invoke the tool as per instructions

hholtmann on hhMacBookPro2014 in ~/proj/iw/openAPI/cmms 
➜  odata2openapi -drp metadata.xml
undefined:1
{"openapi":"3.0.0","info":{"title":"OData Service for namespace Default","version":"","description":"This OData service is located at [http://localhost/service-root/](http://localhost/service-root/)\n\n## Entity Data Model\n![ER Diagram](http://yuml.me/diagram/class/[POReceiptDTO{bg:orange}],[POReturnDTO{bg:orange}],[MeterReadingDTO{bg:orange}],[PurchaseOrderDTO{bg:orange}],[PurchaseOrderLineItemDTO{bg:orange}],[PurchaseRequestDTO{bg:orange}],[PurchaseRequestLineItemDTO{bg:orange}],[PartCheckOutDTO{bg:orange}],[PartReturnDTO{bg:orange}],[PartQuickReceiveDTO{bg:orange}],[WorkOrderDTO{bg:orange}],[WorkRequestDTO{bg:orange}],[InventoryDTO{bg:orange}],[AccountDTO{bg:orange}],[PartDTO{bg:orange}],[PartVendorDTO{bg:orange}],[PartTypeDTO{bg:orange}],[VendorDTO{bg:orange}],[WorkOrderLaborDTO{bg:orange}],[WorkOrderMaterialDTO{bg:orange}],[WorkOrderServiceDTO{bg:orange}],[PartAdjustDTO{bg:orange}],[PartCycleCountDTO{bg:orange}],[StockLocationDTO{bg:orange}],[EquipmentDTO{bg:orange}],[SystemDTO{bg:orange}]

SyntaxError: Unexpected token , in JSON at position 156367
    at JSON.parse (<anonymous>)
    at xslt4node.transform (/Users/hholtmann/proj/iw/odata-openapi/tools/transform.js:142:66)

What else can I provide to help get past this.

The instructions are NOT clear how to force an OData v3.0 $metadata XML file to Open Data JSON file that works?

What am I doing wrong?

**Comment by ralfhandl** [comment]
Hi Heston,

I don't think you are actually doing anything wrong. 

The error message complains about an unexpected comma, so I assume that your client's $metadata contains a construct where the transformation expected something to always be there (and thus continued after it with a leading comma) that actually isn't there in this special case.

If sending me the $metadata file is not an option you could 
* first validate your client's $metadata file against the OData V3 XML schema to verify it is formally correct
* try to guess from the position of the offending comma which XML construct is causing the issue, and send me an "anonymized" example

Thanks in advance
Ralf

**Comment by HestonHoltmann** [comment]
Hi Ralf... thanks for the prompt reply.. no problem giving you the $metadata output form the service.. its attached to this message, added .txt extension to be allowed.

[mvp_plant.xml.txt](https://github.com/oasis-tcs/odata-openapi/files/1559803/mvp_plant.xml.txt)

Does the transform script auto-detect the OData version in the $metadata stream and use the correct transform, or do I have to provide a switch to force OData 3.0 to Swagger output?  This OData source is from OData 3.0 service.

**Comment by ralfhandl** [comment]
Hi Heston,

The problem is caused by this entity type

```xml
      <EntityType Name="EnterpriseSyncDTO">
        <Property Name="SyncData" Type="Collection(CMMSdg.Plant.MappingObjects.PublicDTO.PlantSync)" Nullable="false" />
        <Property Name="Message" Type="Edm.String" />
      </EntityType>
```

It neither declares a key nor inherits (directly or indirectly) from a base type that declares a key. Entity types MUST have a key, either directly defined or inherited from a base type, and the script expects to find at least one key property per entity type.

Just out of curiosity: did your client get this OData service to work?

Thanks in advance
Ralf

**Comment by HestonHoltmann** [comment]
I don't have any real world data/info on the level my client's OData API service is being used by their customers with their product, i suspect its very small and probably only a handful of the API's are used. Most of the API's actually work when I tested them using Postman requests by hand though.  All my attempts at using the commercial and available OData Java frameworks have failed due OData 3.0 not bein supported by any of the Java frameworks, and breaking changes between OData 3.0 and 4.0.  This is why I am trying to convert the OData EDM $metadata model to Swagger/OpenAPI spec file so I can make us of the many OpenAPI import tools that will generate a Java SDK that gets me 90% of the job done.

Since this offending API is not the critical, I could hand modify the output $metadata file, remove the offending Entity and try again until it works?

**Comment by HestonHoltmann** [comment]
I removed the offending EntityType node and any other node refernces to it in the $metadata file (there were 2) and re-ran the tool and no errors. I am experimenting with 15 day free trial of RESTunited.com service that can import OpenAPI/Swagger spec files and auto-generated Java Framework SDK and tests for the api.

**Comment by ralfhandl** [comment]
Closed because issue is not caused by this tool.
