### ISSUE TITLE
$batch resource generation from v4 metadata to open API spec

### ISSUE THREAD

**Issue by chinmayarath** [oasis-tcs/odata-openapi#30]
Hi,

Could you please help to understand the $batch resource generation from v4 metadata to open API spec? For [v4-transformed-catalog.xml.txt](https://github.com/oasis-tcs/odata-openapi/files/3270874/v4-transformed-catalog.xml.txt), the "BatchSupported" annotation is not present. Still the $batch resource appear in the generated open API spec.

cheers,
Chinmaya

**Comment by ralfhandl** [comment]
The assumption is that most OData services support $batch. Services that don't support it can be annotated with BatchSupported:false.

**Comment by chinmayarath** [comment]
Hi @ralfhandl, Thank you for the confirmation, I have a v2 metadata which I convert to v4 using the xslt provided in this repo then apply the open api xslt on the generated v4.

**Comment by ralfhandl** [comment]
@chinmayarath How did you build your V2 service?

**Comment by chinmayarath** [comment]
@ralfhandl V2 Service is SAP gateway Catalog-v2 service on ES5 system.

**Comment by chinmayarath** [comment]
@ralfhandl please find [sample v2 xml](https://github.com/oasis-tcs/odata-openapi/files/3275923/odatav2-catalog-service.xml.txt)

**Comment by chinmayarath** [comment]
@ralfhandl Could you please mark this issue under question label?
