### ISSUE TITLE
It gives error for the contained entity as its key is hidden

### ISSUE THREAD

**Issue by amyzhousap** [oasis-tcs/odata-openapi#31]
I am generating OpenAPI specification from the edmx using the transform script by "odata-openapi -dpo 2.0 WorkforceAPI.xml", but it gives error for the contained entity as its key is hidden.

I have attached files as attached. As .xml file is not supported to upload, I have changed it to WorkforceAPI.txt to upload.WorkforceAPI.xml

[WorkforceAPI.txt](https://github.com/oasis-tcs/odata-openapi/files/3305457/WorkforceAPI.txt)

![Error](https://user-images.githubusercontent.com/30688538/59755020-cf895600-92b9-11e9-8d12-0c4f99e32ec3.png)

**Comment by ralfhandl** [comment]
Hi @amyzhousap,

Entity types without key are only allowed in OData V4.01, and then only for singletons and single-valued navigation properties.

Your WorkforceAPI claims to be OData V4: `<edmx:Edmx Version="4.0">`, and it also uses the keyless entity types in collection-valued navigation properties:
```
        <NavigationProperty Name="emails" Type="Collection(WorkforceAPI.Emails)"
```

Either add a key to entity type `Emails` or make `Emails` a `<ComplexType>` and `emails` a `<Property>`.

Kind regards
Ralf

**Comment by amyzhousap** [comment]
Hi @I067140, Could you please help to check @ralfhandl comments also?
