### ISSUE TITLE
OData V2 sap:semantics="subscriptions" & EntityType/sap:semantics="notifications"

### ISSUE THREAD

**Issue by sterlp** [oasis-tcs/odata-openapi#317]
Hello Guys,

we try to deploy the SAP API Multichannel Foundation for Utilities using the original OData V2 file from SAP
 
https://api.sap.com/api/UT_ERP_ISU_UMC_0001/overview
[Multichannel Foundation for Utilities.zip](https://github.com/user-attachments/files/18078707/Multichannel.Foundation.for.Utilities.zip)

And I get this errors:
```
|- xlan error for: -IN sap-odata-converter/odata-openapi/odata.xml -OUT sap-odata-converter/odata-openapi/odata-V2-to-V4.xml
file://sap-odata-converter/odata-openapi/V2-to-V4-CSDL.xsl; Line #1202; Column #18; EntityType/sap:semantics="subscriptions"
file://sap-odata-converter/odata-openapi/V2-to-V4-CSDL.xsl; Line #1202; Column #18; EntityType/sap:semantics="notifications"
```
Could it be, that this tags aren't supported and not ignored? My current workaround was do remove this tags before I call the converter. Not sure which impact this will have.

Tanks

Paul

**Comment by ralfhandl** [comment]
@sterlp Hi Paul,

When running the converter via command `odata-openapi`, these are just warnings and the OpenAPI output looks correct to me.

Clone the repo, then

~~~sh
cd odata-openapi/tools
npm i -g
odata-openapi path/to/your/xml
~~~

Hope this helps

**Comment by nilskasseckert** [comment]
Hi @ralfhandl 
The problem is that this warning appears on the stderr pipe and cannot be automatically distinguished from an error. 
Can't the warnings be marked with “WARN:” or similar prefixes? Then I could filter them out. Or do you have a better idea?

Regards
Nils

**Comment by ralfhandl** [comment]
Hi @nilskasseckert,
#318 will write xsl:message output to stderr.

Now you can decide which of these messages can be safely ignored in your use cases.

Hope this helps!

**Comment by sterlp** [comment]
Thanks a lot @ralfhandl !
