### ISSUE TITLE
FunctionImport Parameters as "in:query" instead of "in:path"

### ISSUE THREAD

**Issue by bastianStr** [oasis-tcs/odata-openapi#319]
Hi,

we use this script to generate an openapi Spec. For FunctionImport Inputparameters it will create "in":"path". But we need here "in":"query", because we use it in URI like .../functionname?parameter=value .

is it possible to change this? Or how can we achive this?

Kind regards
Bastian

Edit: I forgot to say. The Metadata XML comes out of a SAP System.

**Comment by ralfhandl** [comment]
Hi @bastianStr,

This syntax for function (import) calls was introduced in OData version 4.01.

If your CSDL file states using this OData version (`<Edmx "Version=4.01"` or `{ "$Version": "4.01"`), then the OpenAPI file will use this call syntax.

If your CSDL file states `4.0`, then the parentheses style will be used because it is the only syntax defined by this OData version.

See for example the `ProductsByRating` function import in [examples/csdl-16.1.xml](https://github.com/oasis-tcs/odata-openapi/blob/main/examples/csdl-16.1.xml) that results in

https://github.com/oasis-tcs/odata-openapi/blob/0b4afb4498c7e8c4a4bf146140c7bf1c06376eb4/examples/csdl-16.1.openapi3.json#L1875-L1885

Which kind of SAP system, ABAP or CAP or ...?

Thanks in advance

**Comment by bastianStr** [comment]
HI @ralfhandl ,

thanks for the fast reply!

It is an ABAP SAP System with a V2 Odata Service. It is pretty old, but we need the openapi Spec for controlling a service call from outside. And the System checks very carefully...

Kind regards

**Comment by ralfhandl** [comment]
For OData V2 input the function import parameters are generated as query parameters:

https://github.com/oasis-tcs/odata-openapi/blob/0b4afb4498c7e8c4a4bf146140c7bf1c06376eb4/examples/odata-rw-v2.openapi3.json#L1406-L1417

Which of the two converters are you using: the JavaScript-based or the XSLT-based?

**Comment by bastianStr** [comment]
I use the XSLT based converter. I already copied the newest xslt Transformations (convert v2 to v4, and then V4 to openapi) into my sap system for converting the file. Unfortunately, it doesn't work here:
![image](https://github.com/user-attachments/assets/9e32cf41-2cc3-4813-9ae0-16491dcd4e90)

Should I send you the metadata.xml file which SAP creates? In it it says "edmx V1". maybe thats the problem...

**Comment by ralfhandl** [comment]
Do you set the `odata-version` parameter for the V4-CSDL-to-OpenAPI transformation to `2.0`?

https://github.com/oasis-tcs/odata-openapi/blob/0b4afb4498c7e8c4a4bf146140c7bf1c06376eb4/tools/V4-CSDL-to-OpenAPI.xsl#L44

This is what the JavaScript wrapper does after extracting the version from the XML input:

https://github.com/oasis-tcs/odata-openapi/blob/0b4afb4498c7e8c4a4bf146140c7bf1c06376eb4/tools/transform.js#L155

**Comment by bastianStr** [comment]
No, I didn't. I tried it and the result is strange:

![image](https://github.com/user-attachments/assets/6b56a119-9251-4c81-a3cf-b63dd1a341d4)
 ...

**Comment by bastianStr** [comment]
Ok, maybe I see a problem. We use XSLT V2-to-V4-CSDL.xsl to convert our XML to V4. And then the FunctionImport Parameter are outside EntityContainers:
![image](https://github.com/user-attachments/assets/b4dd1700-1f02-4937-a287-79ab27147ea4)
Inside they would be in:query.

**Comment by ralfhandl** [comment]
Sorry, the full choreography (which is encoded in `transform.cmd` and `transform.js`) is
- detect which OData version the input XML has
- if `2.0` or `3.0`: convert it to V4 XML first
- convert the (intermediate) V4 XML to OpenAPI and tell the XSLT which version the initial input had

**Comment by bastianStr** [comment]
Doh! When I do it right, it works...

I don't converted it to V4, because I thought it can now transform V2 then...my fault. 

Now it works, like it should. Thank you very much for your help!

**Comment by ralfhandl** [comment]
I actually tried to describe this in https://github.com/oasis-tcs/odata-openapi/tree/main/tools#write-your-own-script.

Suggestions on how to improve this description are highly welcome!
