### ISSUE TITLE
Generated openApi specification doesn't produce any compileable java client

### ISSUE THREAD

**Issue by mcfly77** [oasis-tcs/odata-openapi#32]
I created a simple oData Service on SEGW and took the service description from http://...$metadata, looks like that: [odata-service-description.xml](https://1drv.ms/u/s!An8msqHTGD1jg9YiplcoFMhA-UtuWA?e=xZyv10)

This oData Service description produced the following openApi Spec in json: [odata-service-description.openapi3.json](https://1drv.ms/u/s!An8msqHTGD1jg9YjLixtad_7EAUqyQ?e=LaNNHG)

Neigther with https://editor.swagger.io/ nor with openApi generator project it's possible to generate a java client from the produced openApi Json.

I use openapi generator as follows:

`git log -n 1 origin/master
commit dda2f3c1413fe020aa881c3423f24e0c2198859c (HEAD -> master, origin/master, origin/HEAD)
Author: xxx
Date:   Wed Jul 3 12:38:06 2019 +0200`

`mvn clean package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] openapi-generator-project                                          [pom]...`

`java -jar modules\openapi-generator-cli\target\openapi-generator-cli.jar generate -i odata-service-description.openapi3.json -g jaxrs-cxf-client -o .\generated-client`

An attempt to compile the client produced returns the following error: [compile-log.txt](https://1drv.ms/t/s!An8msqHTGD1jg9Yks_mhU11s-H4YRg?e=lbIVBU)

https://editor.swagger.io/ doesn't give any response when trying to generate a client from the given json.

Have i got the workflow correctly? Is there anything wrong with the inital oData Service document or do need to go search for some library issues or do i require a certain version of this project?

I used the follow version of odata-openapi

`D:\...\data\project\odata-openapi>git log -n 1 origin/master
commit 191fda7544168df3d7f622c680833e74555c6105 (HEAD -> master, origin/master, origin/HEAD)
Author: xxxx
Date:   Wed Jul 3 11:39:47 2019 +0200`

Thanks in Advance!
Franz

**Comment by mcfly77** [comment]
I don't understand the details, but it's related to the anyOf definition of the key fields at the components structure definition.

```json	"components": {
		"schemas": {
			"ZTEST_OPENAPI_SERVICE_SRV.contractType": {
				"title": "contractType",
				"type": "object",
				"properties": {
					"contractId": {
						"anyOf": [
							{
								"type": "integer"
							},
							{
								"type": "string"
							}
						],
						"format": "int64",
						"example": "42"
					},
					"description": {
						"type": "string"
					}
				}
			}, 
```

when i remove the anyOf definition and replace it by pure integer like this it works fine:

``` json
	"components": {
		"schemas": {
			"ZTEST_OPENAPI_SERVICE_SRV.contractType": {
				"title": "contractType",
				"type": "object",
				"properties": {
					"contractId": {
						"type": "integer",
						"format": "int64",
						"example": "42"
					},
					"description": {
						"type": "string"
					}
				}
			},
```
Is there any change to suppress generation of anyOf in structure definition?

Thanks!

**Comment by ralfhandl** [comment]
Hi @mcfly77,

The Java client generator you are using apparently cannot deal with the [new `anyOf` construct](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#schema-object) that was added in OpenAPI 3.0.0.

However you are lucky: your service is an OData V2 service and always represents Edm.Int64 numbers as strings. Apparently you didn't provide the XSL transformation parameter `odata-version`: doing this will avoid the then unnecessary `anyOf` construct.

Attached is what I get from your XML file: [odata-service-description.openapi3.zip](https://github.com/oasis-tcs/odata-openapi/files/3355801/odata-service-description.openapi3.zip).

Hope this helps
Ralf

**Comment by mcfly77** [comment]
Thanks a lot. Meanwhile I removed them manually.
How do I set the parameter?
To run odata-openapi3 i used:
```shell
git clone https://github.com/oasis-tcs/odata-openapi.git
npm install -g
odata-openapi3 <source-file> 
```
I don't see how to pass the parameter.

Another thing, if it's to OT please remind me. How's the payload of the oData Service response transformed into the openApi Schema?
If I do a get request against the service i get the oData compliant response:
```json
{
    "d": {
        "results": [
            {
                "__metadata": {
                    "id": "http://vhcalnplci.dummy.nodomain:8000/sap/opu/odata/SAP/ZTEST_OPENAPI_SERVICE_SRV/contract(1l)",
                    "uri": "http://vhcalnplci.dummy.nodomain:8000/sap/opu/odata/SAP/ZTEST_OPENAPI_SERVICE_SRV/contract(1l)",
                    "type": "ZTEST_OPENAPI_SERVICE_SRV.contractType"
                },
                "contractId": "1",
                "description": "First Contract"
            },
            {
                "__metadata": {
                    "id": "http://vhcalnplci.dummy.nodomain:8000/sap/opu/odata/SAP/ZTEST_OPENAPI_SERVICE_SRV/contract(2l)",
                    "uri": "http://vhcalnplci.dummy.nodomain:8000/sap/opu/odata/SAP/ZTEST_OPENAPI_SERVICE_SRV/contract(2l)",
                    "type": "ZTEST_OPENAPI_SERVICE_SRV.contractType"
                },
                "contractId": "2",
                "description": "Another one"
            },...
```
At the example of [northwind](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/Northwind.openapi3.json) however the result is aligned with the schema description from the openApi description.
Can you please give me a hint how this is achieved?

Thanks and Regards,
Franz

**Comment by ralfhandl** [comment]
Ah, sorry, but the new pure JavaScript implementation you installed does not support OData V2. Forgot to mention that in the README, added this restriction now.

Please use one of the older, XSLT-based tools from https://github.com/oasis-tcs/odata-openapi/tree/master/tools for OData V2 services, e.g. transform.js. Please follow the installation instructions to the letter, especially regarding node-gyp.
