### ISSUE TITLE
oData V2 to oData V4 / OpenAPI 3.0

### ISSUE THREAD

**Issue by treee111** [oasis-tcs/odata-openapi#33]
Hello,

I generated a metadata document of a oData service defined in SAP. This document is oData v2.
Now I try to convert this file to a OpenAPI document to process further. The conversion from v2 to v3 should be done automatically as I thought and found in the coding of the transform files.

When trying with command "odata-openapi3", there is a error, that only oData v3 is supported, when trying "odata-openapi", there appears an error:
![cmd_6tOcoBarHi](https://user-images.githubusercontent.com/53038537/61443595-1d8d8a00-a94a-11e9-9fdf-97949c219403.png)

My .xml files begins with:
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="1.0" xmlns:edmx="http://schemas.microsoft.com/ado/2007/06/edmx" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:sap="http://www.sap.com/Protocols/SAPData">
 <edmx:Reference Uri="http://<SERVER>:8000/sap/opu/odata/IWFND/CATALOGSERVICE;v=2/Vocabularies(TechnicalName='%2FIWBEP%2FVOC_COMMON',Version='0001',SAP__Origin='LOCAL')/$value" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
  <edmx:Include Namespace="com.sap.vocabularies.Common.v1" Alias="Common"/>
 </edmx:Reference>
 <edmx:DataServices m:DataServiceVersion="3.0">
  <Schema Namespace="<NAMESPACE>" xml:lang="de" sap:schema-version="1" xmlns="http://schemas.microsoft.com/ado/2008/09/edm">

Do you have any advice on how to proceed. Or do I do it the wrong way?

Thanks in advance for your help.
Greetings

**Comment by ralfhandl** [comment]
The error occurs somewhere in the nodeJavaBridge, so maybe node-gyp is not correctly installed. 

Please follow the [installation instructions](https://github.com/oasis-tcs/odata-openapi/tree/master/tools#installation), especially the part for node-gyp, to the letter.

**Comment by treee111** [comment]
Thank you for the fast response! Java JDK was not installed successfully. After installint openJDK 12, which crashed I installed openJDK 11. Before, i went through the node-gyp Installation and followed method 2.
Deleting odata-openapi, cloning again and installing did the job.

Got the command "odata-openapi" working - Thanks!
