### ISSUE TITLE
Incomplete definition generated from OData Metadata

### ISSUE THREAD

**Issue by azuraka** [oasis-tcs/odata-openapi#36]
There is one operation called POST /CustomerHeaderSet that we are currently using. In the generated Swagger JSON (2.0), we see that a schema called "**CustomerHeader (for create)**" gets added, but it only has the association properties and not the properties from the CustomerHeader payload object schema.

![api_designer_bad_yaml_1](https://user-images.githubusercontent.com/6442501/66111753-2572d700-e5e7-11e9-8353-728021c45aa4.png)

**Comment by ralfhandl** [comment]
Hi @azuraka,

The `xxx-create` structure is a subset of the `xxx` structure that omits all properties that are explicitly marked as "computed" or "read-only". 

For a more detailed analysis of your case I would need the `$metadata` XML file.

Thanks in advance
Ralf

**Comment by azuraka** [comment]
That was indeed the problem. sap:creatable="false".
Thanks for pointing this out.
