### ISSUE TITLE
Support for deep/nested $expand

### ISSUE THREAD

**Issue by snebjorn** [oasis-tcs/odata-openapi#37]
While the documentation states that's it's too [complex](http://docs.oasis-open.org/odata/odata-openapi/v1.0/cnprd01/odata-openapi-v1.0-cnprd01.html#_Toc463874439)
> Note: the syntax of the system query options $expand, $select, and $orderby is too flexible to be formally described with OpenAPI Specification means, yet the typical use cases of just providing a comma-separated list of properties can be expressed via an array-valued parameter with an enum constraint, as shown in the following example. This makes it easy to try out these system query options in OpenAPI tools.

I think a _naive_ solution it possible. For example currently this is generated for `$expand`

```json
{
  "name": "$expand",
  "in": "query",
  "description": "Expand related entities",
  "explode": false,
  "schema": {
    "type": "array",
    "uniqueItems": true,
    "items": {
      "type": "string",
      "enum": ["toFoos"]
    }
  }
}
```
But traversing the XML `NavigationProperty`s it could probably be turned into
```
"enum": ["toFoos", "toFoos/toBars", "toFoos/toBars/toBazs"]
```

**Comment by ralfhandl** [comment]
@snebjorn nice idea, I'll give it a thought.

**Comment by ralfhandl** [comment]
I tried it in branch https://github.com/oasis-tcs/odata-openapi/tree/deep-select, and the very first example service (TripPin) can't deal with paths:

https://services.odata.org/TripPinRESTierService/(S(t01tvbiadsbhhepzg0e0jb1p))/People?$select=FirstName,AddressInfo/City 

returns an error.

So I'm not going to merge this branch, and I'm also disinclined to adding a command line switch for this feature.

Sorry!

**Comment by snebjorn** [comment]
Hmm that's strange.
That's a `$select=complexColProperty/complexProperty` query which is valid according to [the spec](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part2-url-conventions/odata-v4.0-errata02-os-part2-url-conventions-complete.html#_Toc406398163)

Wonder if it works for `navigationProperties`

**Comment by ralfhandl** [comment]
No, doesn't work with $expand either. The issue is known and being worked on. I will continue in a branch and defer merging until _the_ reference service supports it.

**Comment by ralfhandl** [comment]
Actually the OData V4 syntax for nested $expand is `$expand=FirstLevel($expand=SecondLevel(...))`, which has the drawback that you can't combine these nested expressions with a multi-select listbox.

So this might eventually work for deep $select and not for deep $expand.

**Comment by snebjorn** [comment]
I believe OData V2 supports the `/` $expand syntax. Perhaps that can be leveraged when generating for `odata-version=2`

The work required might not be worth it though 🏋

**Comment by ralfhandl** [comment]
I built the deep-select feature only into the new JavaScript implementation, which does not support OData V2.
