### ISSUE TITLE
Is Edmx schema support readonly properties or Entities

### ISSUE THREAD

**Issue by moh-hassan** [oasis-tcs/odata-openapi#40]
I try to read edmx schema to know if property is readonly, so I can generate property as:
  
               public string FullName {get;}      //readonly property

I didn't find readonly in [Odata v4 standard](http://docs.oasis-open.org/odata/odata/v4.0/os/part1-protocol/odata-v4.0-os-part1-protocol.html)

Is Odata standard provide specs for   readonly properties or Entities?

**Comment by ralfhandl** [comment]
If a property is annotated with [Core.Computed](https://github.com/oasis-tcs/odata-vocabularies/blob/master/vocabularies/Org.OData.Core.V1.md#Computed), it is read-only.

**Comment by moh-hassan** [comment]
Thanks @ralfhandl .
Your answer with the example helped me to resolve my issue.
