### ISSUE TITLE
Dependency sax-js  doesn't support custom entities in xml

### ISSUE THREAD

**Issue by tsg2k2** [oasis-tcs/odata-openapi#41]
XML Entities are useful to express some repeated sets of annotations (like disabling support for all $* parameters on the endpoint) and just reference them. sax.js doesn't support those. https://github.com/Leonidas-from-XIV/node-xml2js/issues/443
It makes sense to use another parser.

**Comment by ralfhandl** [comment]
The use of custom XML entities is strongly discouraged, see https://issues.oasis-open.org/browse/ODATA-461. 

Unfortunately the publication of the corresponding Committee Note has been delayed so far.

**Comment by tsg2k2** [comment]
My usecase doesn't require exposing csdl. Only the produced openapi doc
will be published. Is there a different way to set capabilities defaults?
Like 'all of my entity sets do not support $filter'

**Comment by ralfhandl** [comment]
Unfortunately not.

**Comment by tsg2k2** [comment]
So the support for inline entities is still necessary, it seems. May be as
opt-in feature?

**Comment by ralfhandl** [comment]
You could write a pre-processor that expands your XML entities.
