### ISSUE TITLE
Enumerations for $select,$expand, and $orderby do not include BaseType's properties

### ISSUE THREAD

**Issue by tsg2k2** [oasis-tcs/odata-openapi#42]
Generated $select,$expand, and $orderby enums should include BaseType's properties (recursively)

**Comment by ralfhandl** [comment]
Fixed.

@tsg2k2 please check and close issue if it works for you

**Comment by tsg2k2** [comment]
It works, after the fix above

**Comment by ralfhandl** [comment]
Thanks for catching this!
