### ISSUE TITLE
$batch endpoint is still using $ prefix even for 4.01+ schemas 

### ISSUE THREAD

**Issue by tsg2k2** [oasis-tcs/odata-openapi#44]
Query parameters do not have $ prefix anymore (as expected). $batch endpoint  should also have no prefix.

**Comment by ralfhandl** [comment]
Hi  @tsg2k2, this is correct, see https://github.com/oasis-tcs/odata-abnf/blob/master/abnf/odata-abnf-construction-rules.txt#L90.

The `$` prefix is not optional for resource names such as `$batch` and `$metadata` to avoid collision with names of entity sets etc.
