### ISSUE TITLE
Error: Cannot find module '/opt/openapi/odata-openapi-master/tools/node_modules/java/build/Release/nodejavabridge_bindings.node'

### ISSUE THREAD

**Issue by thneumann** [oasis-tcs/odata-openapi#47]
Hi,

I just did the installation as described. However, when I want to execute 
`odata-openapi -db metadata.xml`
I receive the following error message:
`Error: Cannot find module '/opt/openapi/odata-openapi-master/tools/node_modules/java/build/Release/nodejavabridge_bindings.node'`
I checked this repository and found out that there is not even a 'build' directory. So 
`build/Release/nodejavabridge_bindings.node` is completely missing.
Did I do something wrong during installation. Have you had such a problem?
I really appreciate any help.
Best regards

Edit:
As this might has something to do with Java, here are some information about my Version:
`javac -version
javac 1.8.0_231`
`java -version
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)`

Edit2:
There have been 2 Warnings during installation:
npm WARN lifecycle java@0.11.1~install: cannot run in wd java@0.11.1 node-gyp rebuild (wd=/opt/openapi/odata-openapi-master/tools/node_modules/java)
npm WARN lifecycle java@0.11.1~postinstall: cannot run in wd java@0.11.1 node postInstall.js (wd=/opt/openapi/odata-openapi-master/tools/node_modules/java)
+ odata-openapi-xslt@0.0.0
added 21 packages from 19 contributors and updated 1 package in 2.65s

**Comment by ralfhandl** [comment]
The installation of the old XSLT-based tool is rather brittle, especially on Windows.

1. If your service uses OData version 3.0 or 4.0, **do not use the old XSLT-based tool** that requires Java, instead use the new pure JavaScript tool https://github.com/oasis-tcs/odata-openapi/tree/master/lib. 

2. If your service uses OData version 2.0, you are unfortunately stuck with the old tool.
    - Make sure Java is in the `PATH`
    - Install node-gyp and follow the platform-specific instructions to the letter. On Windows use Option 1
    - Then and only then run `npm install` in the `tools` folder

Java 1..8.0 works for me.

**Comment by thneumann** [comment]
Thanks you for your answer,
unfortunately, we are still on OData version 2.0 and we are not sure whether the SAP standard allows us to change it easily to v4.0.
I already installed this library on another server on node 10.15.3 half a year ago without any problems. So I installed nvm and installed 10.15.3 and faced the same issue:
```
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.4.178-94.91-default
gyp ERR! command "/root/.nvm/versions/node/v10.15.3/bin/node" "/root/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/openapi/odata-openapi-master/tools/node_modules/java
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! java@0.11.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.11.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

However, I was able to transfer the node 10.15.3. compiled ../tools/node_modules/java/build/ dir from the old server to the new server. Now it is working fine. However, I couldn't find out why the java integration is not working.

**Comment by ralfhandl** [comment]
No idea. Similar problems in the past were always solved by **literally** following the [platform-specific installation instructions for node-gyp](https://github.com/nodejs/node-gyp/blob/master/README.md#installation).

**Comment by kvrsaicharan** [comment]
i am also facing the same issue , did you solved this

**Comment by ralfhandl** [comment]
@kvrsaicharan Please try the new pure JavaScript tool https://github.com/oasis-tcs/odata-openapi/tree/master/lib. Its installation is much easier.
