### ISSUE TITLE
OpenApi does not generate (ODataV3)

### ISSUE THREAD

**Issue by navaddins** [oasis-tcs/odata-openapi#5]
Hi,

I try to generate openapi (aka swagger) file from attached odata metadata xml. File is generated but it does not include other document.

Cmd

> odata2openapi -drp MyMetadata.xml

File result
```
{
    "openapi": "3.0.0",
    "info": {
        "title": "OData CSDL Document for namespace ",
        "version": "",
        "description": ""
    },
    "paths": {},
    "components": {}
}
```

Here is my meatadata xml
[MyMetadata.txt](https://github.com/oasis-tcs/odata-openapi/files/1578298/MyMetadata.txt)

Is it anything wrong on odata metadata xml format?

Regards,

**Comment by ralfhandl** [comment]
Hi @navaddins,

Your MyMetadata.txt uses the CSDL 1.0 namespace:

        <Schema Namespace="NAV" 
            xmlns="http://schemas.microsoft.com/ado/2007/05/edm">

The transformation however only recognizes the CSDL 2.0 and CSDL 3.0 namespaces
* http://schemas.microsoft.com/ado/2008/09/edm
* http://schemas.microsoft.com/ado/2009/11/edm

Replacing the CSDL 1.0 namespace in MyMetadata.txt with any of the two recognized namespaces works fine.

Regards
Ralf

**Comment by yukonn** [comment]
Thanks for your suggestion. Now,it's working fine.

Regards,
Yukon
