### ISSUE TITLE
Invalid conversion of OData metadata to Swagger 2.0

### ISSUE THREAD

**Issue by azuraka** [oasis-tcs/odata-openapi#54]
Hi Ralf,

We have an OData metadata v2 content. We are converting it into V4 first. And then converting that V4 content to swagger 2.0.

I have attached the content respectively. The conversion of V4 content to swagger 2.0 generates an invalid JSON file (PFA).

[GeneratedSwaggerContent.json.txt](https://github.com/oasis-tcs/odata-openapi/files/3998157/GeneratedSwaggerContent.json.txt)
[CatalogServiceODataV2.xml.txt](https://github.com/oasis-tcs/odata-openapi/files/3998158/CatalogServiceODataV2.xml.txt)

Can you help us know the issue here?

**Note:-** In the V4-CSDL-to-OpenAPI.xsl, we have changed:
<xsl:param name="openapi-version" select="'3.0.0'" />
to
<xsl:param name="openapi-version" select="'2.0'" />
as we wanted to generate swagger 2.0 content.

**Comment by ralfhandl** [comment]
Hi @azuraka,

Your attached XML file converts fine with the latest transformation:

[CatalogServiceODataV2.openapi.json.txt](https://github.com/oasis-tcs/odata-openapi/files/4018892/CatalogServiceODataV2.openapi.json.txt)

The resulting Swagger 2.0 JSON validates and displays in Swagger UI without warnings.

Not sure what issue you are seeing.

Thanks in advance
Ralf

**Comment by ralfhandl** [comment]
Problem seems to be caused by the XSLT processor built into Java, use [Xalan-Java](https://xalan.apache.org/xalan-j/index.html) instead.

For Python [lxml.etree](https://lxml.de/xpathxslt.html#xslt) seems to work.

For ABAP the built-in [XSLT processor](https://help.sap.com/viewer/31bfc625c2674acdb9aa7547b62db9cc/7.52.5/en-US/a8824c3c66177414e10000000a114084.html) works.

**Comment by kvrsaicharan** [comment]
how did you convert odata v2 to v4 ? can you explain me

**Comment by ralfhandl** [comment]
The XSL transformation https://github.com/oasis-tcs/odata-openapi/blob/master/tools/V2-to-V4-CSDL.xsl converts OData V2 $metadata to OData V4 $metadata. 

It is called under the hood by https://github.com/oasis-tcs/odata-openapi/blob/master/tools/transform.js
