### ISSUE TITLE
Nullable Data Types are not valid against Swagger Specification

### ISSUE THREAD

**Issue by ttrapp** [oasis-tcs/odata-openapi#6]
The [swagger specification](https://swagger.io/docs/specification/data-models/data-types/) says:

> OpenAPI 3.0 does not have an explicit null type as in JSON Schema, but you can use nullable: true to specify that the value may be null. Note that null is different from an empty string “”. 
> # Correct
> type: integer
> nullable: true
> 
> # Incorrect
> type: null
> 
> # Incorrect as well
> type:
>   - integer
>   - null

When you expose a ABAP CDS view using auto exposure  then all properties are nullable except the primary key of view. As result the nullable attribute of the property is not "false" and the XSL transformations create something like "type":["string","null"] which is incorrect.

**Comment by ralfhandl** [comment]
The transformation can produce OpenAPI 3.0.0 as well as OpenAPI 2.0, and by default it produces OpenAPI 2.0. Use XSL parameter `openapi-version` to control the output version, e,g. `-PARAM openapi-version 3.0.0` on a XALAN command line.

OpenAPI 2.0 allows array values for `type`, and most Swagger tools support it. This style is used for 2.0 output, e.g. https://github.com/oasis-tcs/odata-openapi/blob/master/examples/csdl-16.1.openapi.json#L1127

OpenAPI 3.0.0 does not allow array values for `type` and instead introduces the `nullable` keyword. This is style is used for 3.0.0 output, e.g. https://github.com/oasis-tcs/odata-openapi/blob/master/examples/csdl-16.1.openapi3.json#L1413
