### ISSUE TITLE
SAP OData missing __count property

### ISSUE THREAD

**Issue by snebjorn** [oasis-tcs/odata-openapi#61]
I'm working with an ODATA endpoint in SAP and I noticed that SAP sends a `__count` property when `$inlinecount` is used, which isn't described in the $metadata unfortunately. Not sure if it can be "turned on" via a query parameter. However it's there.

I looked though the XSLT scripts and couldn't find a "handler" for the __count property. Is it possible to add this to the generated OAS when converting a metadata from SAP OData?

The reason why the `__count` property is relevant when paging because it contains the total number of results on the server (not a count of returned) which is needed when displaying how many pages there are.

![image](https://user-images.githubusercontent.com/1266245/73930401-b845ba00-48d6-11ea-89c5-3a0c93cc0b63.png)

The SAP ODATA response looks like this:

```jsonc
{
  "d": {
    "__count": "42", // shows up when $inlinecount is added
    "results": [...]
  }
}
```

This is odata-version=2. Not sure how it'll look when going to v4 and using `$count`

**Comment by ralfhandl** [comment]
In OData V4.01 it would look like this, see [OData JSON Format, 13 Collection of Entities](https://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#sec_CollectionofEntities):

```json
{
  "@count": 37,
  "value": [
    { ... },
    { ... },
    { ... }
  ]
}
```

And in V4 it would be `@odata.count`. 

For OData V2 the place to add `__count` would be here: https://github.com/oasis-tcs/odata-openapi/blob/master/tools/V4-CSDL-to-OpenAPI.xsl#L1587.

For V4.0x it would be here: https://github.com/oasis-tcs/odata-openapi/blob/master/tools/V4-CSDL-to-OpenAPI.xsl#L4247, and here: https://github.com/oasis-tcs/odata-openapi/blob/master/lib/csdl2openapi.js#L1283.

A pull request for this feature would be highly welcome.

Unfortunately I don't have an automated test for the XSLT version at the moment. For the newer JavaScript version just use `npm run test` (or easier: `mocha --watch`) in the package root.

**Comment by ralfhandl** [comment]
Added simple test script https://github.com/oasis-tcs/odata-openapi/blob/master/tools/test.cmd

Runs XSLTs for a bunch of test input files and uses git diff to show what has changed.

**Comment by snebjorn** [comment]
Many thanks for the points and the test script, it helped a lot :)
