### ISSUE TITLE
Edm.Decimal gets to number and string

### ISSUE THREAD

**Issue by ttrapp** [oasis-tcs/odata-openapi#7]
The following OData V2 property will be transformed in a wrong way:

`<Property Name="gross_amount" Type="Edm.Decimal" Precision="16" Scale="3" sap:unit="currency_code" sap:label="Gross Amount" sap:heading="Total Gross Amount" sap:quickinfo="EPM: Total Gross Amount"/>`

The result is

`gross_amount":{"type":["number","string","null"],"format":"decimal","multipleOf":1.0e-3,"title":"Gross Amount","description":"EPM: Total Gross Amount"`

IMHO it should become a number with nullable attribute.

**Comment by ralfhandl** [comment]
OData V2 renders Edm.Decimal values as JSON strings, so [string,null] would be sufficient. 

OData V4 renders Edm.Decimal values as JSON numbers, with the exception of INF, -INF, and NaN, which are rendered as strings, thus [number,string,null].
