### ISSUE TITLE
$metadata payload change odata.context base host url

### ISSUE THREAD

**Issue by ccdevcreative** [oasis-tcs/odata-openapi#72]
Hi there,
For **api hosted (on premise) behind a load balancer or api gateway,** the uri in the payload for document services and entity response **(@odata.context,@odata.link),** is the uri on the from the hosted server and not the url from the api gateway(etc).

I found a way to change the url on the entity responses metadata,but not for the document services...

 **Question:** There are some alternative for change this url to the hosted base url?

**Comment by ccdevcreative** [comment]
More details about my doubt...

Thanks so much for answer my comments...

I was able to write the services document payload in a file, but what i need is to have the same out
image
https://user-images.githubusercontent.com/31016910/76540565-ad8fbf00-6458-11ea-8adb-7692f197ba18.png

But, what i need is to replicate the same in the services document response
image

https://user-images.githubusercontent.com/31016910/76540727-ed56a680-6458-11ea-8cf2-e00e389075d5.png

I'm linking here a simple sample dot net core api project (with the default weather controller and entity)... for you can check and see what i'm missing
https://github.com/ccdevcreative/ODataOnPremise.git

Thanks so much again...

**Comment by ralfhandl** [comment]
Sorry, this question relates to the OData framework you are using, in which I am not involved.
