### ISSUE TITLE
Simplify installation 🚀

### ISSUE THREAD

**Issue by snebjorn** [oasis-tcs/odata-openapi#75]
It's pretty hard to get this tool up and running. I was wondering if it was possible to simplify the node version in the tools folder.

> It uses xslt4node, which in turn needs node-gyp and a Java SE JDK.

And node-gyp requires python and windows-build-tools it's a bit much.

I found [Saxon-JS](http://www.saxonica.com/saxon-js/documentation/index.html#!api/transform) which claims
> Saxon-JS is an XSLT 3.0 run-time written in pure JavaScript.

There might be a license issue, however their [license](http://www.saxonica.com/saxon-js/documentation/index.html#!conditions) says this
> no license is needed for run time deployment on a web browser

Which I guess node sort if is :) 

Anyway would you be interested in replacing xslt4node with something a bit easier to install?

WASM is also a possibly.

**Comment by snebjorn** [comment]
Turns out Saxon-JS doesn't run on Node yet https://stackoverflow.com/questions/50984147/saxonjs-on-node-js
They're working on it, but it seems to take a while.

It might be faster to just wrap and existing solution in WASM :)

**Comment by ralfhandl** [comment]
I already replaced the whole XSLT stuff in the new pure JavaScript version of the tool in https://github.com/oasis-tcs/odata-openapi/tree/master/lib.

It is much cleaner, literally 1000 times faster (measured with [Microsoft Graph](https://developer.microsoft.com/en-us/graph)'s $metadata), and easy to install.

**Comment by snebjorn** [comment]
oh I figured there were some limitations on that since it didn't support the odata v2 convertions

**Comment by ralfhandl** [comment]
Yes, it does not support OData V2 - that would require fifty-ish `if` statements which I am not eager to add 😈 

The underlying XML parser from https://github.com/oasis-tcs/odata-csdl-schemas/tree/master/lib already can digest OData V2.

**Comment by snebjorn** [comment]
Perhaps I misunderstand. Can the XML parser i /lib do XSLT transformations? Cause it thought it could only convert xml to json.

**Comment by ralfhandl** [comment]
This package works on CSDL JSON only and uses the `odata-csdl` package to convert XML input first.

The `odata-csdl` package can convert OData V2, V3, and V4 CSDL XML into CSDL JSON.

**Comment by ralfhandl** [comment]
The XSLT-based tool now no longer requires node-gyp, so installation should run smoothly.
