### ISSUE TITLE
Error generating YUML diagram using Javascript version

### ISSUE THREAD

**Issue by deenar** [oasis-tcs/odata-openapi#78]
Not sure if I am doing something wrong

$ odata-openapi3 -d ~/Downloads/metadata.xml 
Downloads/metadata.openapi3.json
/dev/odata-openapi-master/lib/csdl2openapi.js:249
                            const bidirectional = property.$Partner && target && target[property.$Partner].$Partner == propertyName;
                                                                                                           ^

TypeError: Cannot read property '$Partner' of undefined
    at dev/odata-openapi-master/lib/csdl2openapi.js:249:108
    at Array.forEach (<anonymous>)
    at dev/odata-openapi-master/lib/csdl2openapi.js:244:74
    at Array.forEach (<anonymous>)
    at dev/odata-openapi-master/lib/csdl2openapi.js:239:18
    at Array.forEach (<anonymous>)
    at resourceDiagram (/dev/odata-openapi-master/lib/csdl2openapi.js:236:62)
    at info (dev/odata-openapi-master/lib/csdl2openapi.js:214:24)
    at Object.module.exports.csdl2openapi (dev/odata-openapi-master/lib/csdl2openapi.js:59:15)
    at convert (dev/odata-openapi-master/lib/cli.js:72:25)

**Comment by ralfhandl** [comment]
Please check whether the Partner attributes in your metadata.xml correctly point to navigation properties in the target entity type:
* if entity type `A` has a navigation property `to_B` of type `B` with a Partner attribute `to_A`
* then entity type `B` must have a navigation property `to_A`

**Comment by ralfhandl** [comment]
Ok, crash avoided with latest version. It should now silently ignore the Partner attribute.

**Comment by deenar** [comment]
@ralfhandl many thanks for the prompt response, i will pull the changes and try again

**Comment by ralfhandl** [comment]
@deenar please close this issue once you've successfully tested the fix. 

Thanks in advance!

**Comment by deenar** [comment]
Successfully tested, many thanks
