### ISSUE TITLE
OData 4 produces invalid JSON

### ISSUE THREAD

**Issue by vminnocci** [oasis-tcs/odata-openapi#8]
Using http://services.odata.org/TripPinRESTierService/(S(x4ntlpt0jotx2ttqxrzytzir))/$metadata 
produces invalid JSON and fails using pretty print which could be an additional clue.   I also found this true for my OData 4 metadata service
[foo.zip](https://github.com/oasis-tcs/odata-openapi/files/1952074/foo.zip)

**Comment by ralfhandl** [comment]
Both TripPinRESTierService and foo.xml work for me, using transform.cmd from a Windows command line, result is [TripPinRestier.openapi3.zip](https://github.com/oasis-tcs/odata-openapi/files/1952709/TripPinRestier.openapi3.zip)

foo.xml in foo.zip is identical to TripPinRestier $metadata, and it also works (no wonder :-)

Which conversion tool did you use?

**Comment by vminnocci** [comment]
I'm on Linux and I used both transform and odata2openapi and they both yielded the same results.

Sent from Yahoo Mail on Android 
 
  On Thu, Apr 26, 2018 at 3:37 PM, Ralf Handl<notifications@github.com> wrote:   
Both TripPinRESTierService and foo.xml work for me, using transform.cmd from a Windows command line, result is TripPinRestier.openapi3.zip

foo.xml in foo.zip is identical to TripPinRestier $metadata, and it also works (no wonder :-)

Which conversion tool did you use?

**Comment by vminnocci** [comment]
I'm going to try Windows as well. Thanks for your time and help

Sent from Yahoo Mail on Android 
 
  On Thu, Apr 26, 2018 at 3:37 PM, Ralf Handl<notifications@github.com> wrote:   
Both TripPinRESTierService and foo.xml work for me, using transform.cmd from a Windows command line, result is TripPinRestier.openapi3.zip

foo.xml in foo.zip is identical to TripPinRestier $metadata, and it also works (no wonder :-)

Which conversion tool did you use?

**Comment by ralfhandl** [comment]
Try `./transform` while in folder `tools` to make sure you start the right command.

**Comment by ralfhandl** [comment]
Should be fixed with https://github.com/oasis-tcs/odata-openapi/commit/9b131d0d272447a7ba49ff07bccdf0fb6ea6aec5, please check

**Comment by vminnocci** [comment]
I'll give it a try.  Thanks for you help

**Comment by vminnocci** [comment]
Hello Ralf!  Thanks for the fix, unfortunately I see new errors regarding missing schemas.  On a side note we are trying to convert OData 4 metadata to OpenAPI3 json.  Is your tool in a place where we can do that? 
    On Wednesday, May 2, 2018, 11:46:27 AM EDT, Ralf Handl <notifications@github.com> wrote:  
 
 
Should be fixed with 9b131d0, please check

**Comment by ralfhandl** [comment]
OData V4 is the preferred input format. In fact V2 and V3 require an additional transformation step to an intermediate V4 metadata file, which is done under the hood by the scripts.

**Comment by vminnocci** [comment]
OK. 
Here is the error I'm getting when running the attached file with the following transform.txt
parse error: unallowed token at this point in JSON text                                        {"openapi":"3.0.0","info":{"ti                     (right here) ------^parse error: unallowed token at this point in JSON text                                        {"swagger":"2.0","info":{"titl                     (right here) ------^

Thanks again for your help! Ralf!    On Friday, May 4, 2018, 10:06:51 AM EDT, Ralf Handl <notifications@github.com> wrote:  
 
 
OData V4 is the preferred input format. In fact V2 and V3 require an additional transformation step to an intermediate V4 metadata file, which is done under the hood by the scripts.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
    
# XML metadata files to transform into OpenAPI JSON
# file scheme host service-root odata-version

# specification example services
#csdl-16.1.xml      http localhost /service-root
#csdl-16.2.xml      http localhost /examples
#ExampleService.xml http localhost /service-root 
#miscellaneous.xml  http localhost /service-root
#aggregation.xml    http localhost /Sales.svc

# cross-service examples
#People.xml   http localhost /People.svc
#Products.xml http localhost /Products.svc

# live services at www.odata.org
#example.xml   http services.odata.org /V4/OData/(S(nsga2k1tyctb0cn0ofcgcn4o))/OData.svc
#Northwind.xml http services.odata.org /V4/Northwind/Northwind.svc
#TripPin.xml   http services.odata.org /V4/(S(cnbm44wtbc1v5bgrlek5lpcc))/TripPinServiceRW

# live V2 service at www.odata.org
#odata-rw-v2.xml  http services.odata.org /V2/(S(j4g3x2g225evharuxieq0ay3))/OData/OData.svc V2
#Northwind-V2.xml http services.odata.org /V2/Northwind/Northwind.svc                       V2

# live V3 service at www.odata.org
#odata-rw-v3.xml  http services.odata.org /V3/(S(1urrjxgkuh4r30yqim0hqrtj))/OData/OData.svc V3
#Northwind-V3.xml http services.odata.org /V3/Northwind/Northwind.svc                       V3

# key-as-segment examples
#Northwind-key-as-segment.xml http services.odata.org /V4/Northwind/Northwind.svc

# live V4 services
#graph.xml https graph.microsoft.com /v1.0 V4
qa-4-metadata.xml http localhost /test V4

**Comment by ralfhandl** [comment]
Can you please send me the metadata file, I can't find an attachment.

**Comment by vminnocci** [comment]
Sorry - Here you go.
    On Friday, May 4, 2018, 12:10:07 PM EDT, Ralf Handl <notifications@github.com> wrote:  
 
 
Can you please send me the metadata file, I can't find an attachment.

**Comment by ralfhandl** [comment]
Sorry, still no attachment. Can you upload it to this issue, similar to foo.zip on the initial post on this issue?
I'll look into it on Monday.

**Comment by ralfhandl** [comment]
Hi Vico,

Cause of the error was an entity set with an entity type without a key definition: neither AL7_REPORT_FORMAT nor its abstract base type REPORT_FORMAT defines a key, and REPORT_FORMAT also doesn't have a base type. Without a key you can't have an entity set in OData.

The transformation now detects and logs this modeling error and produces well-formed JSON with `ERROR: neither key nor base type` strings as stand-in for the missing key. 

The transformation now also deals more gracefully with invalid default values: `0`, `1`, `no`, `No`, and `Yes` aren't valid default values for Edm.Boolean, only `true`, `false`, and `null` are allowed. In general default values have to be type-compatible, so e.g. `Now` isn't valid for Edm.DateTimeOffset even if it doesn't lead to XML or JSON validation errors.

Please try out https://github.com/oasis-tcs/odata-openapi/commit/16c811418039aa5e420d61fce918a07240d8c4cb.

Thanks!
Ralf

**Comment by vminnocci** [comment]
Awesome Ralf! 

Sent from Yahoo Mail on Android 
 
  On Sun, May 6, 2018 at 8:48 AM, Ralf Handl<notifications@github.com> wrote:   
Hi Vico,

Cause of the error was an entity set with an entity type without a key definition: neither AL7_REPORT_FORMAT nor its abstract base type REPORT_FORMAT defines a key, and REPORT_FORMAT also doesn't have a base type. Without a key you can't have an entity set in OData.

The transformation now detects and logs this modeling error and produces well-formed JSON with ERROR: neither key nor base type strings as stand-in for the missing key.

The transformation now also deals more gracefully with invalid default values: 0, 1, no, No, and Yes aren't valid default values for Edm.Boolean, only true, false, and null are allowed. In general default values have to be type-compatible, so e.g. Now isn't valid for Edm.DateTimeOffset even if it doesn't lead to XML or JSON validation errors.

Please try out 16c8114.

Thanks!
Ralf

**Comment by vminnocci** [comment]
Ralf,It looks like it generated a 3 spec file.  My next goal is to view the file in Swagger.  Do you recommend other tools for generating Swagger UI from OpenAPI3?-Vico
    On Sunday, May 6, 2018, 1:42:29 PM EDT, Vico Minnocci <vminnocci@yahoo.com> wrote:  
 
 Awesome Ralf! 

Sent from Yahoo Mail on Android 
 
  On Sun, May 6, 2018 at 8:48 AM, Ralf Handl<notifications@github.com> wrote:   
Hi Vico,

Cause of the error was an entity set with an entity type without a key definition: neither AL7_REPORT_FORMAT nor its abstract base type REPORT_FORMAT defines a key, and REPORT_FORMAT also doesn't have a base type. Without a key you can't have an entity set in OData.

The transformation now detects and logs this modeling error and produces well-formed JSON with ERROR: neither key nor base type strings as stand-in for the missing key.

The transformation now also deals more gracefully with invalid default values: 0, 1, no, No, and Yes aren't valid default values for Edm.Boolean, only true, false, and null are allowed. In general default values have to be type-compatible, so e.g. Now isn't valid for Edm.DateTimeOffset even if it doesn't lead to XML or JSON validation errors.

Please try out 16c8114.

Thanks!
Ralf

**Comment by ralfhandl** [comment]
Swagger UI 3.x, available at https://github.com/swagger-api/swagger-ui, already supports OpenAPI 3.0.1 out of the box.

**Comment by vminnocci** [comment]
Resolved.  Thanks Ralf.
