### ISSUE TITLE
Deep insert and expanded entity

### ISSUE THREAD

**Issue by mukherjee0707** [oasis-tcs/odata-openapi#84]
Currently in ODATA V2.0, we can create deep insert and expanded entity and correspondingly use POST method to post the data into SAP backend.
However when we try to use the transformation to generate OPENAPI spec for the API and publish it in Swagger, no POST methods are shown.
How can this be manipulated in the transformation?

**Comment by ralfhandl** [comment]
@mukherjee0707 Please check whether the entity sets are annotated with `sap:creatable="false"`. This annotations suppresses `POST` for insert operation.

**Comment by mukherjee0707** [comment]
> @mukherjee0707 Please check whether the entity sets are annotated with `sap:creatable="false"`. This annotations suppresses `POST` for insert operation.

Thanks @ralfhandl  It works....

**Comment by mukherjee0707** [comment]
@ralfhandl  
I am trying something on my side.
Based on the metadata from ODATA service, I use the transformation to generate an openAPI specification. Now in deep insert there are few entity types which are used but the associated methods are not relevant for the consumer side.

When the generated OPENAPI spec is put in the swagger editor, it shows the methods available. How do we hide the GET methods from the deep insert segments and also how do we hide the schemas of the internal segment of deep insert. We dont want to show the internal segments as separate schemas. 

Attached is the schema and the screnshot of swager editor print.
[Data.zip](https://github.com/oasis-tcs/odata-openapi/files/4910920/Data.zip)

**Comment by ralfhandl** [comment]
@mukherjee0707 please check https://github.com/oasis-tcs/odata-openapi/blob/master/doc/FAQ.md#how-do-i-suppress-get-list-and-by-key-on-an-entity-set for how to suppress GET methods. An example is available here: https://github.com/oasis-tcs/odata-openapi/blob/master/examples/annotations.xml#L461-L465

Currently there's no way to mark a navigation property as "does not support deep insert".

**Comment by mukherjee0707** [comment]
I have tries adding this but doesn't seems to work..
![image](https://user-images.githubusercontent.com/39399561/87395955-cb6c5c80-c5cf-11ea-821f-63cf1f71f4fd.png)

Am i missing something?

**Comment by ralfhandl** [comment]
@mukherjee0707 The annotation target is not complete: entity sets are children of an entity container, so the full target is 
_namespace_`.`_container_`/`_set_, in your case
```xml
<Annotations Target="Z_ORDER_ELIGIBILITY_SRV.Z_ORDER_ELIGIBILITY_SRV_Entities/GeneralSet">
```

**Comment by mukherjee0707** [comment]
@ralfhandl 
Changed the target... but still doesn't hide the GET methods .
![image](https://user-images.githubusercontent.com/39399561/87398905-33bd3d00-c5d4-11ea-8033-71d35fddca91.png)

**Comment by ralfhandl** [comment]
@mukherjee0707 Please cross-check your metadata with this example: https://github.com/oasis-tcs/odata-openapi/blob/master/tools/tests/annotations.xml

In [lines 461-466](https://github.com/oasis-tcs/odata-openapi/blob/master/tools/tests/annotations.xml#L461-L466) you find an example for "Readable=false", which works as proven by https://github.com/oasis-tcs/odata-openapi/blob/master/tools/tests/annotations.openapi3.json

**Comment by mukherjee0707** [comment]
@ralfhandl 
I have tried everything from comparing the metadata with that given by you.
But still could not figure out the issue..

Can you please have a look at the metadata and let me know the issue if possible?
[metadata.txt](https://github.com/oasis-tcs/odata-openapi/files/4927335/metadata.txt)

**Comment by ralfhandl** [comment]
@mukherjee0707 for me it works fine, no GET operations for the entity sets you marked with `Readable:false`.

[metadata.openapi3.txt](https://github.com/oasis-tcs/odata-openapi/files/4929770/metadata.openapi3.txt)

If you want to get rid of the remaining GET operations for nested segments, please take a look at https://github.com/oasis-tcs/odata-openapi/blob/master/tools/tests/annotations.xml#L284 and adjust accordingly.

> how do we hide the schemas of the internal segment of deep insert

There's no way to hide schemas, they are generated independently of the operations.

**Comment by mukherjee0707** [comment]
@ralfhandl 
I have added the annotations in the metadata.
![image](https://user-images.githubusercontent.com/39399561/87663057-d9adaa80-c780-11ea-8a44-5bdbd52acd9f.png)

However no result.
Could it be that I am using the navigation path and property incorrectly.
Essentially I want to get rid of the following segments in JSON.
![image](https://user-images.githubusercontent.com/39399561/87663283-35783380-c781-11ea-94b0-461e36ac60a8.png)

**Comment by ralfhandl** [comment]
Hi @mukherjee0707, please try `Bool="false"` to hide GET operations.

**Comment by mukherjee0707** [comment]
@ralfhandl Same result with Bool:"False".

**Comment by ralfhandl** [comment]
@mukherjee0707 is the `<Annotations Target="Z_ORDER_ELIGIBILITY_SRV.Z_ORDER_ELIGIBILITY_SRV_Entities/GeneralSet"`?

**Comment by mukherjee0707** [comment]
@ralfhandl 
I have tried with both <Annotations Target="Z_ORDER_ELIGIBILITY_SRV.Z_ORDER_ELIGIBILITY_SRV_Entities/GeneralSet" and also with the child segments.
[metadata.txt](https://github.com/oasis-tcs/odata-openapi/files/4932607/metadata.txt)

**Comment by ralfhandl** [comment]
@mukherjee0707 Problem was `sap:addressable="false"` on the "nested" entity sets: `sap:addressable=false` removes direct read on entity set and allows indirect read via navigation.

Attached is a repaired metadata plus the resulting openapi3 file:
- [_mukherjee0707.xml.txt](https://github.com/oasis-tcs/odata-openapi/files/4933962/_mukherjee0707.xml.txt)
- [_mukherjee0707.openapi3.json.txt](https://github.com/oasis-tcs/odata-openapi/files/4933963/_mukherjee0707.openapi3.json.txt)

**Comment by mukherjee0707** [comment]
@ralfhandl 
Thank You. But when I check the addressable flag in the entity set it comes back with a other GET methods in the OPEN API spec.
[metadata.txt](https://github.com/oasis-tcs/odata-openapi/files/4935543/metadata.txt)
[Open API JSON.txt](https://github.com/oasis-tcs/odata-openapi/files/4935544/Open.API.JSON.txt)

Essentially, the conversion happens via the transformations, so is it possible that you can point out where in the transformation, the suppression occurs in the transformation so that I can have a look in debug what is going on?

**Comment by ralfhandl** [comment]
@mukherjee0707 

> when I check the addressable flag in the entity set it comes back with a other GET methods

Yes, you have to turn these off via additional `ReadRestrictions`.

> point out where in the transformation

The [V2-to-V4 transformation](https://github.com/oasis-tcs/odata-openapi/blob/master/tools/V2-to-V4-CSDL.xsl) treats `sap:addressable="false"` as a shortcut for "no direct read here, and all indirect reads are allowed". And there's no way to get rid of the now explicitly allowed indirect reads. Only way is to _not_ use `sap:addressable="false"` and only use `ReadRestrictions` wherever you want to have them.
