### ISSUE TITLE
Missing schemas

### ISSUE THREAD

**Issue by vminnocci** [oasis-tcs/odata-openapi#9]
When running the transform shell I get the following errors

`error:  Cannot find schema '/home/vminnocci/Documents/code/OpenAPI-Specification/schemas/v2.0/schema.json'
example
error:  Cannot find schema '/home/vminnocci/Documents/code/odata-openapi/tools/openapi-3.0.0.schema.json'
error:  Cannot find schema '/home/vminnocci/Documents/code/OpenAPI-Specification/schemas/v2.0/schema.json'
Northwind
error:  Cannot find schema '/home/vminnocci/Documents/code/odata-openapi/tools/openapi-3.0.0.schema.json'
error:  Cannot find schema '/home/vminnocci/Documents/code/OpenAPI-Specification/schemas/v2.0/schema.json'
TripPin
error:  Cannot find schema '/home/vminnocci/Documents/code/odata-openapi/tools/openapi-3.0.0.schema.json'
error:  Cannot find schema '/home/vminnocci/Documents/code/OpenAPI-Specification/schemas/v2.0/schema.json'
odata-rw-v2
error:  Cannot find schema '/home/vminnocci/Documents/code/odata-openapi/tools/openapi-3.0.0.schema.json'
error:  Cannot find schema '/home/vminnocci/Documents/code/OpenAPI-Specification/schemas/v2.0/schema.json'
Northwind-V2
error:  Cannot find schema '/home/vminnocci/Documents/code/odata-openapi/tools/openapi-3.0.0.schema.json'
error:  Cannot find schema '/home/vminnocci/Documents/code/OpenAPI-Specification/schemas/v2.0/schema.json'
odata-rw-v3
error:  Cannot find schema '/home/vminnocci/Documents/code/odata-openapi/tools/openapi-3.0.0.schema.json'
error:  Cannot find schema '/home/vminnocci/Documents/code/OpenAPI-Specification/schemas/v2.0/schema.json'
Northwind-V3
error:  Cannot find schema '/home/vminnocci/Documents/code/odata-openapi/tools/openapi-3.0.0.schema.json'
error:  Cannot find schema '/home/vminnocci/Documents/code/OpenAPI-Specification/schemas/v2.0/schema.json'
Northwind-key-as-segment
error:  Cannot find schema '/home/vminnocci/Documents/code/odata-openapi/tools/openapi-3.0.0.schema.json'
error:  Cannot find schema '/home/vminnocci/Documents/code/OpenAPI-Specification/schemas/v2.0/schema.json'
`

**Comment by ralfhandl** [comment]
The shell script uses a JSON Schema validator ([ajv-cli](https://www.npmjs.com/package/ajv-cli)) to check the produced OpenAPI JSON files. The schemas for OpenAPI 2.0 and 3.0.1 are not part of this project, so the script assumes that the OpenAPI-Specification project has been cloned next to this project, see [tools/README.md](https://github.com/oasis-tcs/odata-openapi/blob/master/tools/README.md).

I've added a check for existence of the schema files and skip validation if they aren't in the expected location in https://github.com/oasis-tcs/odata-openapi/commit/c194c2756e107df3f36ab4eb8f495ce8c3653142, please try it out.
